### ISSUE TITLE
Talent Roll Table Entries with Broken Links

### ISSUE THREAD

**Issue by ZurielRedux** [Muttley/foundryvtt-shadowdark#137]
I have noticed that a few of the Rolls on the Talent Table have broken item links.

So far I have noted:
Fighter - Weapon Mastery Item
Priest - +1 to Spellcasting Checks
Thief - Backstab bonus die
Wizard - +1 to Spellcasting Checks. Also, the 12 result does not list +1 to spellcasting checks as an option.

**Comment by Muttley** [comment]
I'll go through these and check them before release.
