### ISSUE TITLE
Feature: System tutorials through the Tour system

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#139]
**Why?**
To help new users of the system to quickly get a hang of it.

**What?**
- [-] General setup
  - [x] How to roll weapon attacks
- [x] Lightsource tracker
- [x] Manual restoration of spells
- [-] Talents (split to #257)
- [x] The Lost Citadel import
- [x] Dice rolling
  - [x] Create temporary actor, make a roll
  - [x] Indication of Advantage
  - [x] Backstabbing

**Comment by WisdomOfWombats** [comment]
The lightsource tracker is the most obviously confusing, I think. An explanation of this really niffty feature would probably be best.

**Comment by Muttley** [comment]
This is probably most confusing for people trying to test out the system in a new world, there's not too much to it though.

@WisdomOfWombats 
As it will be useful when making the tutorials, here are a few things to know about the Light Tracker:

1. It will only track light sources on the sheets of Player actors that are currently claimed by a player as their character (not just ownership permissions)
2. By default it will *only* track the lightsources of Players who are actually online, *unless* you enable the "Track Inactive User Lightsources" in the system settings.
3. By default, the time remaining on a light source will not decrease when the game is paused, *unless* you uncheck the "Pause Light Tracking" (how evil do you want to be?).
4. Only light sources that have been lit will show on the tracker.
5. When a light source expires it will be removed from the token, and the inventory of the player
6. You can toggle individual lights off on the track by pressing the flame icon, or you can douse them all at once by pressing the button.

**Comment by bakbakbakbakbak** [comment]
Closing this with the creation of #257
