### ISSUE TITLE
Manually Adding Active Effects seems unresponsive

### ISSUE THREAD

**Issue by ZurielRedux** [Muttley/foundryvtt-shadowdark#142]
When editing or creating a new talent, you can click below Talent Type(s) and get a menu of effects, but after you make your selections the save button does not do anything and even if you manually close the dialog it does not update.

**Comment by Muttley** [comment]
This is a Foundry issue with ActiveEffects.  You can't edit ActiveEffects on an item already owned by a character.  You'll need to create one in the side bar.

I'm actually going to remove the "add" button from talents to avoid confusing people.
