### ISSUE TITLE
Backstab doesn't work for higher level

### ISSUE THREAD

**Issue by WisdomOfWombats** [Muttley/foundryvtt-shadowdark#143]
Create a thief, equip a weapon, set level to 2 or higher. 
Click on weapon
In the roll dialog check Backstab box
Then click "normal" roll

System shows exactly two dice being rolled for damage. But it should be 1 + 1/2 level rounded down.

**Comment by Muttley** [comment]
Did you drag the backstab talent from the Talents compendium?

**Comment by Muttley** [comment]
> 

Actually, if you're second level then it *should* roll two dice...

**Comment by Muttley** [comment]
OK, I've seen it now.  Definitely not working (it was last night) ;)
