### ISSUE TITLE
Weapon Mastery not correctly displayed on the Abilities tab in the Attacks section

### ISSUE THREAD

**Issue by WisdomOfWombats** [Muttley/foundryvtt-shadowdark#145]
When a fighter has weapon mastery for a weapon, the system automatically increases the to hit bonus by exactly +1. But it should be increased by 1 + 1/2 level rounded down. In the roll dialog, it is shown correctly.

**Comment by Muttley** [comment]
Possibly related to #143 @bakbakbakbakbak ?
