### ISSUE TITLE
Nice to have: Abilities Tab: Attack section - Finesse weapons should be shown with their correct attack bonus

### ISSUE THREAD

**Issue by WisdomOfWombats** [Muttley/foundryvtt-shadowdark#154]
Finesse weapons (okay, currently there is only the dagger) should be shown with the higher of Str or Dex bonus. The roll dialog works fine.

**Comment by Muttley** [comment]
They should be with the latest release if you check again.

**Comment by WisdomOfWombats** [comment]
Yes, they are. Issue can be closed. Thanks. 👍
