### ISSUE TITLE
Bug with Max HP when adding Stout to the character sheet

### ISSUE THREAD

**Issue by WisdomOfWombats** [Muttley/foundryvtt-shadowdark#155]
As soon as I add Stout to a character, I cannot increase the Max HP anymore. When I change HP, Max HP reverts to whatever it was before the increase to Max HP. Makes levelling up hard to do, unless I am missing something.

1) Write in MaxHP (note the value)
2) Add Stout
3) Increase MaxHP (e.g. due to level up)
4) Change HP
5) Max HP changes back to the value at Step 1

**Comment by Muttley** [comment]
Related to #110
