### ISSUE TITLE
Enhancement: NPC Special Attacks are not rollable

### ISSUE THREAD

**Issue by Rexus39** [Muttley/foundryvtt-shadowdark#184]
Ettercap Web Attack doesn't work when you click it.

**Comment by bakbakbakbakbak** [comment]
We should clarify this in the documentation, but the there are "Special attacks" for the NPCs, and Web is one of them. They are not clickable as there is nothing to roll for them. However, looking at it, I am getting confused by the +2 on the attack there.

I do see an enhancement to do there, that is to enable rolling Special features with the attack bonus, but skipping the damage roll.

**Comment by Muttley** [comment]
Yes, we should definitely enable rolls for specials somehow.

**Comment by PrototypeESBU** [comment]
**Usage**: To support GMs ease of communicating unique monster abilities, add a function to quickly display a non-rollable special feature to chat. 
See mockup:
![mockup](https://github.com/Muttley/foundryvtt-shadowdark/assets/147362581/b5337dba-d455-4321-9e7f-7a410e980a63)

**Comment by PrototypeESBU** [comment]
@bakbakbakbakbak In review this, I think the ettercap poison web +2 attack bonus is just a typo. My understanding is that monster attacks are special if they don't list a damage value and that they hit automatically. I still think there is value in listing them under attacks, but I'm just going to make a change to have those display the static chat card when clicked and then this issues can be wrapped up.

**Comment by Muttley** [comment]
> @bakbakbakbakbak In review this, I think the ettercap poison web +2 attack bonus is just a typo. My understanding is that monster attacks are special if they don't list a damage value and that they hit automatically. I still think there is value in listing them under attacks, but I'm just going to make a change to have those display the static chat card when clicked and then this issues can be wrapped up.

I don't think they're an instant hit.  It has a +2 to the attack, but there's no immediate damage as it's per-round instead (and being stuck in place).

We should probably clarify with Kelsey though.
