### ISSUE TITLE
Hit Points on PCs

### ISSUE THREAD

**Issue by Rexus39** [Muttley/foundryvtt-shadowdark#185]
Elbin shows as having 7 out of 5 hit points.

Jorbin shows as having 10 out of 8 hit points.

(I saw this using display bar for HP)

**Comment by bakbakbakbakbak** [comment]
@Muttley  I assume this is something related to your work on Stout talents?

**Comment by bakbakbakbakbak** [comment]
Ohh this is interesting, this is due to the token settings. It uses the  `attributes.hp.max` `attributes.hp.value`.

I'll take a look at HP rolling and see if I can figure something out.
