### ISSUE TITLE
Bastard two handed sword rolls both one handed and two handed damage

### ISSUE THREAD

**Issue by Ulitmatex** [Muttley/foundryvtt-shadowdark#186]
Not sure if this is a bug or intended but if you roll a weapon with versatile it rolls both one-handed and two-handed damage instead of the one you select.

![image](https://user-images.githubusercontent.com/77658242/227703142-9ae1c6a4-fe69-489c-a011-043f2e787488.png)

**Comment by bakbakbakbakbak** [comment]
This is functioning as intended, it is implemented this way to speed up combat by reducing clicks for rolls :) However, if you run Dice So Nice, they roll is sequence if that's what you're after!
