### ISSUE TITLE
Feature: Turn off Fog Exploration on maps in system settings

### ISSUE THREAD

**Issue by skotothalamos** [Muttley/foundryvtt-shadowdark#187]
De-selecting Fog Exploration in Foundry Scene Settings turns off the auto-mapping of places you've been but can no longer see. Currently, we could just change the default settings on the Lost Citadel map. Perhaps a system setting could default all newly-made scenes to have Fog Exploration disabled?

**Comment by Muttley** [comment]
I agree with seeing the Lost Citadel Map, but I think new scenes created by GMs should be left to them to decide.
