### ISSUE TITLE
Feature: Level advancements

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#191]
**Why?**
When a user changes the "level" field in their sheet, a dialog could ask them if they want to roll for HP and potentially on talents (if on a talent-level).

**Notes**
Considerations of how to make this scalable with custom classes has to be taken. Are we going to introduce `Class` items that contain the talent table? #71

**Comment by Muttley** [comment]
I think this should really tie into whatever we do for character building

**Comment by PrototypeESBU** [comment]
This has been implemented as the level up app.
