### ISSUE TITLE
Feature: Add a timer to spells

### ISSUE THREAD

**Issue by WisdomOfWombats** [Muttley/foundryvtt-shadowdark#204]
When a character casts a spell with a set duration of rounds, the system displays a timer next to the spell with the remaining rounds.

Added bonus feature: the timer counts down automatically, when it's the characters turn.

**Comment by WisdomOfWombats** [comment]
Would it at least be possible to show a timer field that the user can countdown manually? Otherwise, there is no really good place to track the spell.

**Comment by bakbakbakbakbak** [comment]
This can now be solved by the user creating an associated "Spell Effect" that has the same settings as the spell (See the Spell Effects compendium in 1.3.0 for inspiration). Those effects can then be dragged onto the target or the caster, or whoever you want, and if you're in combat, it will track the duration in the Effect Panel when selecting a token for that actor. 

Closing this with that remark!

**Comment by bakbakbakbakbak** [comment]
See the following clip (And yes, I noticed it says Seconds instead of Rounds!)
https://user-images.githubusercontent.com/105067023/233906628-75262142-3bf7-4aa9-9986-a4dcabc29553.mp4
