### ISSUE TITLE
Talents in Locked Compendium is Editable

### ISSUE THREAD

**Issue by chmking** [Muttley/foundryvtt-shadowdark#209]
Opening a talent from the compendium, clicking on `Active` will remove the effect and clicking on `Talent Type(s)` allows you to edit and save changes to a locked talent. The changes persist between reloads.

**Comment by bakbakbakbakbak** [comment]
oooh this is interesting, I wonder if this works in other systems as well.

I am not sure if we can fix this, perhaps by making restrictions in the `_updateObject` method? in the ItemSheets...

**Comment by Muttley** [comment]
Not just talents.  Anything with a custom form element.
