### ISSUE TITLE
Feature: Initiative in and out of combat

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#22]
Do we need it out of combat?

**Comment by git-steve-git** [comment]
The quickstart rules do suggest rolling initiative outside of combat (pg 45, where combat rules don't begin until pg 50 and then mention the concept of "combat initiative.")  However, as far as I can tell, outside of combat it's really just about keeping players organized so they aren't all talking at once.  Even Kelsey and her friends don't seem to strictly adhere to initiative order outside of combat, judging by their actual play videos.

As long as you can roll initiative and have the resulting turn order displayed somewhere for reference, I think that will suffice.  I suspect Foundry's base initiative system could cover this use case itself, although I could be mistaken.

**Comment by bakbakbakbakbak** [comment]
Indeed, if we don't need any special initiative tracking outside combat, this may be a non-issue. I agree with your observations!

**Comment by bakbakbakbakbak** [comment]
Closing this as it was recently closed in #40
