### ISSUE TITLE
Feature: Drag Attacks to Hot Bar

### ISSUE THREAD

**Issue by hlmodking** [Muttley/foundryvtt-shadowdark#220]
Allow players/gm to drag attacks/abilities to the hotbar for easier use.

**Comment by bakbakbakbakbak** [comment]
This should create a roll macro for the item, there are implementations available for systems like dnd5e and ose, so it should be an alright first issue to get started with!

**Comment by bakbakbakbakbak** [comment]
I started tinkering with this yesterday, but it is only easy for dragging weapons. I think we are missing `_onDragStart` methods for Spells, and probably NPC abilities too.

**Comment by bakbakbakbakbak** [comment]
- [ ] Weapon Attacks
- [ ] Spell rolling
- [ ] NPC rollable features
- [ ] Any rollable item?

**Comment by hlmodking** [comment]
Yes to all the above. 

Attacks of any kind
Spells of any kind
Useable items. (potions, scrolls, wands, ect..)

**Comment by sjmiller85** [comment]
Upon dragging items from the inventory page of a character sheet to the hotbar, and then clicking on any of the items, A Foundry error appears, reading "No such item found on character."

I didn't realize that I had to select a character's token first.  Could the Foundry error be amended to clarify that detail for future GM's and players?
