### ISSUE TITLE
Bug: After rolling the hit points with the new functionality, increasing Constitution doesn't change the hp anymore

### ISSUE THREAD

**Issue by WisdomOfWombats** [Muttley/foundryvtt-shadowdark#225]
1) Set up a new character
2) Roll for HP
3) Increase Constitution manually (because you forgot to enter your stats) 
or Add the +2 Constitution talent to the character
4) No effect. The HP remain unchanged

Expected result: the HP increase by the amount the Con bonus increased.

**Comment by bakbakbakbakbak** [comment]
First off, the solution today:
1. We assume the user has setup their stats before their roll HP, and we include the con modifier in the first level roll as that is the only time it changes things.
2. If they realize they didn't set the ability before the roll, they can adjust the HP manually

The alternative solution I see is that we apply the con modifier to the `hp.bonus` field then? That way we can keep that automated all the way, both by the contribution from con modifier, as well as the active effects?

I can't really tell how big of an issue this is right now, and how fast we should prioritize fixing it?

**Comment by WisdomOfWombats** [comment]
I just asked the question on the SD discord. When your Con is raised by a advancement, it retro-actively applies to your hp as well. Solution 1 will be my workaround for today.
Regarding option 2: When I somehow change the HP after rolling with the new functionality, and then advance to 2nd level, and roll the HD for that level, the HP from level 1 revert to their originally rolled value.

**Comment by bakbakbakbakbak** [comment]
I think #227 does allow that @Muttley. And it defaults to not using automation.

**Comment by bakbakbakbakbak** [comment]
And also, yes, the this was tipping over on that side of too much automation indeed :D
