### ISSUE TITLE
Feature: Wands & Spells casting

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#23]
Should calculate the appropriate target value. See` castSpell()`.

After reviewing this #72, and instead of adding a new type of items, basic items with the linked spell in description and with the spell DC indicated for now. If we get requests for this later, we could implement it, but I think the current solution is good enough for initial release at least.

**Comment by bakbakbakbakbak** [comment]
We could jack this into the Scrolls mechanics as they use the same game rules. Scrolls have been implemented as treasure right now, should we do the same for Wands?

**Comment by bakbakbakbakbak** [comment]
This is probably solved by #329

**Comment by Muttley** [comment]
Yeah, #329 will implement this.
