### ISSUE TITLE
Feature: Magic item properties

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#24]
Magic items may have Bonus properties:
- Armor for AC bonus
- Weapons for Attack Bonus and Damage Bonus

**Comment by Muttley** [comment]
Maybe we could use Active Effects on normal Weapon and Armor items to achieve this?

**Comment by bakbakbakbakbak** [comment]
Yeah, we can do that. The `ActiveEffectSD` class has stuff for that, we just need to expose it on a tab or something on the item sheet.

**Comment by bakbakbakbakbak** [comment]
I've started working on this with the effects that are mentioned in the quickstarter guide.

**Comment by bakbakbakbakbak** [comment]
Forgot to close this with #72
