### ISSUE TITLE
Feature: Light Timer

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#25]
**Why?**
In-game light timer built for torch-tracking purpose.

**Ideas**
- Perhaps the module [Hourglass](https://foundryvtt.com/packages/hourglass) could be used as inspiration

**Comment by bakbakbakbakbak** [comment]
This could be implemented using the ActiveEffects implemented for Talents (and prepared for using temporary items).

**Comment by Muttley** [comment]
Well, as you know, the light timer is there now.  We just need to attach/detach light a light from the player's token when a torch is lit/put out.

**Comment by bakbakbakbakbak** [comment]
Yes, I just assigned you to this as I know you're working on it, so my scanning of the issues is faster :D
