### ISSUE TITLE
Feature: Advanced Talent creation Tour

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#257]
Create a guided tour for how building custom talents work, and how talents have to be modified before imported to actors.

The last part may be moot if we implement `_onDropItem` functionality on the character sheets that prompts the user for how to modify the talent before importing it.

split from #139

**Comment by PrototypeESBU** [comment]
Support for tours to be dropped in 2.3.0
