### ISSUE TITLE
Feature: Ability score damage

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#266]
Monsters like the Wight have ability drain abilities.

Some cursed items may have similar effects.

**Comment by Muttley** [comment]
I'm guessing we need to be able to add active effects to the character directly and not just via talents?

**Comment by bakbakbakbakbak** [comment]
Yeah, I need to have a think on this. As I see it spontaneously is that we either introeuce a new type of item that we run something akin to the lightsource tracker, or we utilize statuses somehow.

**Comment by bakbakbakbakbak** [comment]
This is easily implemented with the #276 Effect Overhaul.

I'm going to build a compendium with Conditions, and will create "Condition: Life Drain (1)" up to (4) for e.g. the Wraiths attack. These can then be linked into the attack description and just drag-n-dropped onto either the token or the actor sheet.
