### ISSUE TITLE
Feature: Compiled Compendiums

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#306]
**Why?**
With the PF2e Beastiary token integration, as well as the possibility to map actors to art in version 1.2.0, we need to have strict control over `ids`. While we are at it, we should keep each compendium item/actor/etc. as json files we compile instead of modifying the data in a game world.

**How?**
The PF2e system does this already. We have the data, so what we need to do is write code that can compile compendiums (both for v10 and v11). This would also allow us to keep compatibility across the versions.

**Notes**
Tagging this as a Good first issue as it is fairly isolated, would have the developer familiarize themselves with the template for the files, as well as being able to contribute to fresh new features.

**Comment by bakbakbakbakbak** [comment]
I started extracting the database into separate json files this morning, and started cleaning them up.

**Comment by bakbakbakbakbak** [comment]
Reference implementation for compiling packs to NEDB
https://github.com/foundryvtt/pf2e/tree/master/packs

For compiling packs to LevelDB, see @foundryvtt/foundryvtt-cli

**Comment by Muttley** [comment]
The way `@foundryvtt/foundryvtt-cli` is designed to work seems pretty crap for use at build time.  I think I'm going to have to write my own cli/build tool to manage this stuff.
