### ISSUE TITLE
Bug: Collected Compendia Typos

### ISSUE THREAD

**Issue by git-steve-git** [Muttley/foundryvtt-shadowdark#32]
- Longbow costs 9gp, should be 8gp

- Shortbow has Range set to "Close" (should be "Far"), 1d6 2H damage (should be 1d4), and is missing the actual 2H property

- Multiple backpacks all cost 0 slots.  My understanding is the first one's free, subsequent backpacks are 1 slot each.  Perhaps the Free Carry rules haven't been implemented yet?

- I think it makes more sense for "Flask" and "Bottle" to be two separate items, even though they are functionally identical.  My character is carrying a flask or a bottle, not a "flask or bottle."

- Spells with a duration of days or real time (Light) just have "--" in the Duration field.  Is this intentional?  I think the UX would be better if there was actually a "Days" option.  And maybe "Special" instead of "--" for spells like Charm Person or Light that have unusual/variable durations.

- The Alarm spell description includes an extra paragraph from Alter Self that should be removed.  That same paragraph is missing from the description of Alter Self.

**Comment by Rhydian31** [comment]
@git-steve-git, 5th item, I don't see "--" in the spell.db; was the issue notice on the front end?

similarly, I'm not sure about 3rd item regarding gear slots.

Fixed 1, 2, 4, 6.

**Comment by git-steve-git** [comment]
Yeah, front end.  Basically there's no defined Duration value for spells that have a duration in Days, or for the Light spell (which is the only real-time one.)

**Comment by bakbakbakbakbak** [comment]
@Muttley  : can you chime in on the free carry about backpacks?

**Comment by Muttley** [comment]
> Multiple backpacks all cost 0 slots. My understanding is the first one's free, subsequent backpacks are 1 slot each. Perhaps the Free Carry rules haven't been implemented yet?

Free Carry rules are currently there for Coins/Gems and items with quantities per slot.

Currently we don't calculate this for multiple versions of the main item in different slots.  The workaround right now is on the second backback (why would you want multiple?!) is to edit the second one and set Free Carry to 0.

**Comment by git-steve-git** [comment]
I agree it seems unlikely anyone would want a second backpack anyway.  Especially since they don't give you slots or anything; it's pretty much just thematic to explain where you're putting the rest of your stuff.  I flagged it because it was a difference from the printed rules, but we can skip fixing that one if it's too much trouble.

**Comment by bakbakbakbakbak** [comment]
I'm having a PR that fixes all the above except the free carry & bag question. I will submit after #58 is merged.
