### ISSUE TITLE
Possible Bug: Item types, magic weapons and weapon mastery

### ISSUE THREAD

**Issue by DM-BenC** [Muttley/foundryvtt-shadowdark#325]
If you have a character with weapon mastery in a particular weapon e.g, bastard sword, and you give that character a magic version of the weapon e.g. +1 bastard sword, then even if you set the weapon type to bastard sword on the magic weapon it doesn't count the weapon mastery when it calculates the bonuses. Its almost as if it counts the magic weapon as a new weapon type.

**Comment by Muttley** [comment]
This appears to work correctly, but the attack string in the Abilities tab is not correct.

![image](https://user-images.githubusercontent.com/853835/232340781-9c2dcdd8-61b9-476c-a413-67f33ecbdec8.png)

![image](https://user-images.githubusercontent.com/853835/232340860-a1b79d77-9b14-48de-9340-70ee88932fc0.png)

**Comment by Muttley** [comment]
Correct Item and Talent bonuses shown:
![image](https://user-images.githubusercontent.com/853835/232340989-237958d6-ac05-453e-ae32-db5aeb3740db.png)

**Comment by bakbakbakbakbak** [comment]
Can confirm, it is the string construction for the display that is erroneous. The item still rolls as intended.
