### ISSUE TITLE
Bug: Making new magic weapons

### ISSUE THREAD

**Issue by DM-BenC** [Muttley/foundryvtt-shadowdark#326]
It's possible to make a new magic weapon by copying an existing one and changing its bonuses. It doesn't seem to possible however to make your own new weapons because the Magic Item Effects listing, whilst selectable, doesn't save so you can't actually set any parameters.

**Comment by bakbakbakbakbak** [comment]
The Magic Items will be overhauled with version 1.3.0, this should make this interface more intuitive. Please keep an eye on discord if you are using it, as I'm posting videos of the overhaul. I need help making sure it actually is more intuitive :D

**Comment by bakbakbakbakbak** [comment]
We are locking down the effects IF the item is owned by an actor (See #317) in version 1.3.0.

However, if you import the item and make a copy, modifying it in the Item Sidebar, this should do what you want here.

I'm closing this issue.
