### ISSUE TITLE
Bug: Editing Description of item doesn't render until sheet is rerendered

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#330]
When editing the Description field, the text doesn't show until you refresh the sheet.

Comment for Good First Issue:
- By adding a `sheet.render(false)` somewhere where we handle updates to the sheet, this should be fixed, I think.

**Comment by Muttley** [comment]
Unable to replicate this by editing the description in either the Items sidebar, or on the character sheet, could you give an example workflow that shows the issue?

**Comment by bakbakbakbakbak** [comment]
Oh yes, it was me using `_onSubmit` instead of `_onChangeInput` for the effects. Closing this!
