### ISSUE TITLE
Feature: Support the Pulp Mode (p. 111 Core rules)

### ISSUE THREAD

**Issue by WisdomOfWombats** [Muttley/foundryvtt-shadowdark#343]
Change: when the pulp mode is active, Luck is a number field instead of a checkbox.
Needed: checkbox in the settings dialog to active pulp mode.
Effect: character sheet shows Luck as a number field, when the checkbox to activate the pulp mode is set in the settings.

The pulp mode allows players to have more than 1 luck token.

**Comment by gatesvp** [comment]
Some formal dev notes:
Pulp Mode is presented on Page 111 of the official rules. It has several elements that effect Luck. So implementing it will require a few tweaks at the UI level.

### Requirements

The Pulp mode has exactly 5 bullets. Broken out below by whether or not the Foundry System should handle them

#### Things requiring system changes

> There are no maximum luck tokens a player can have

In this mode, Luck changes from a boolean/checkmark to an actual number. If a DM enables or disables this feature, we should probably reset all luck to `0` to avoid any bad state.

> PCs can use a luck token to force the GM to reroll a roll

Once we get #335 working, I think this is an extra "if" statement. In fact, I think that's a thing to capture on #335.

#### Things the DM can handle

> You can use a luck token to take an extra action
> You can use a luck token to turn a hit into a critical hit
> Players start every session with 1d4 luck tokens.

Each of these points at _some_ potential automation, but without explicit automation support, those are just DM fiat at this point.
