### ISSUE TITLE
Feature: Allow static damage NPC attacks

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#352]
Monsters such as the Rat has 1 damage, with no dice roll.

**Comment by gatesvp** [comment]
I think this is resolved. I was able to make this work by selected "no damage dice" and entering the static damage as the first number.
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/319590/8bba9243-4a83-4233-942f-f8b93af66b2a)

It displays correctly.
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/319590/dd38e368-b305-4972-b550-40a705704cfb)

And it rolls correctly
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/319590/146b105e-0e48-4985-807a-9dca80457eb6)

Move to close this issue.

**Comment by gatesvp** [comment]
Looks like this works. Is there additional work that needs to be done on this ticket?

**Comment by Muttley** [comment]
Although this is a workaround, it's non-intuitive so still needs work.

**Comment by Muttley** [comment]
This ticket would be resolved by doing this: https://github.com/Muttley/foundryvtt-shadowdark/issues/337#issuecomment-1807209777
