### ISSUE TITLE
bug: Blind rolls are not blinded

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#359]
When rolling a "Blind GM Roll", the content of the chat card is expected to be blinded, but that is not happening right now.

Same applies to when sending message; if you choose self-roll and write something, it shows for everyone. Same with Blind GM Roll.

**Comment by Muttley** [comment]
I thought I'd fixed this for normal rolls, apart from Dice So Nice still showing (I think there's a couple of additional flags that need setting).

Certain informational chat messages should always be public though (light stuff, etc.)

**Comment by bakbakbakbakbak** [comment]
Yeah it seems our `rollMode` handling is very janky. Self Rolls show for the GM e.g.

I was playing around with adding a hook that blinds the roll, but it feels like that is just doing something built-in to foundry that I can't find. Perhaps an overhaul of the chatcards in necessary too.

**Comment by bakbakbakbakbak** [comment]
I tested with PF2e, the GM sees the Self Rolls there, so I think you're right!
