### ISSUE TITLE
Errata for Sleep spell

### ISSUE THREAD

**Issue by Muttley** [Muttley/foundryvtt-shadowdark#360]
![image](https://user-images.githubusercontent.com/853835/234202216-1b7fd762-ae86-4ddf-ab97-e67c834f89c5.png)

**Comment by DescendingAngel** [comment]
This does not appear to be resolved. The spell language is out of date as of July 8, 2024 using the item from Compendium>Shadowdark System>Spells>Wizard>Tier 1>Sleep
