### ISSUE TITLE
Compatibility with Monk's Enhanced Journals 

### ISSUE THREAD

**Issue by archdruid101** [Muttley/foundryvtt-shadowdark#366]
I have been testing Monk's Enhanced journals which offers some great in game features such as shops and loot. One problem I found it that the Shadowdark System uses "coins" where as Monks Enhanced Journals and most other systems uses "currency" to identify the coins in the actors inventory, as such Enhanced Journals cannot pull or add coinage to the players when interacting with the shops. Thanks for all your hard work.

**Comment by Muttley** [comment]
This is something that really needs to be raised with the developer of Monk's Enhanced Journals to make this a customisable option as it's a limitation of their module.
