### ISSUE TITLE
Feature: Weapon & Armor type customization

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#37]
**Why?**
Talents like Weapon Mastery, and +1 to Armor of your choice implies that a choice of type has to be made.

**How?**
Initial idea is to have predefined types in the data-models, and/or config. These lists can then be used to generate selection dialogs which then defines a list of talent-activated equipments. These lists can then be parsed by the dice roller to  determine talent bonuses.

To enable customization, we could implement a custom setting in the system settings, allowing the users to add a semi-colon separated list of custom weapon/armor types: `whip;cast iron pan` for example. These could be combined with the data-model types before displaying. This would also be a handy way to expand a sub-type selection dialog for items that this may be relevant to.

**Comment by git-steve-git** [comment]
How difficult would it be to scan for items of the appropriate type in the Items tab of the world, and merge those with the pre-defined list in the data model?

Another consideration would be magic or named variants of basic weapons.  For example, my warrior has a +1 longsword named "Talon."  The item name is "Talon (+1)" but it is mechanically a longsword, so presumably would gain bonuses from Weapon Mastery (longsword) as well.  This may sort of be what you meant by sub-types, not sure.

**Comment by bakbakbakbakbak** [comment]
That is what I am thinking of when ralking about sub-types indeed!

**Comment by bakbakbakbakbak** [comment]
This should be done in conjunction with #68
