### ISSUE TITLE
Feature: Custom Ancestries

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#375]
Potentially autopopulating fields on a Player Actor when dragged onto a sheet. Should contain:

- Description
- Ancestry Talents (inline and linked to predefined talents in compendium)

**Comment by JohnGoure** [comment]
Hey great idea! Ancestries can currently be customized by entering unique text in the Ancestry field. So this is to extend that functionality to create an item of type ancestry that will be used to auto populating the ancestry field?

**Comment by bakbakbakbakbak** [comment]
> Hey great idea! Ancestries can currently be customized by entering unique text in the Ancestry field. So this is to extend that functionality to create an item of type ancestry that will be used to auto populating the ancestry field?

And provide the associated talents or skills, depending on what the ancestry is providing.
