### ISSUE TITLE
Feature: Class Skills

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#376]
These should be rollable, and would be needing to have various fields like:
- Uses per day

These are different than talents that tend to provide passive buffs to characters.

**Comment by JohnGoure** [comment]
Characters would need a learn new skill with a selection of DC 18 Int down to DC 9 Int. 

The pop up needs an input field with the skill name and input field with skill description. If the check is successful then the user can create the skill and add it to their auxiliary skills.

Or is this outside the scope of this feature?

**Comment by bakbakbakbakbak** [comment]
> Characters would need a learn new skill with a selection of DC 18 Int down to DC 9 Int.
> 
> The pop up needs an input field with the skill name and input field with skill description. If the check is successful then the user can create the skill and add it to their auxiliary skills.
> 
> Or is this outside the scope of this feature?

Yeah, I don't recognize that as a rule from the books. If you can refer me to a page, I'll take a look though!
