### ISSUE TITLE
Feature: Add support for importing Ranger class from www.ShadowDarklings.net

### ISSUE THREAD

**Issue by MikeMundy** [Muttley/foundryvtt-shadowdark#387]
I'm just waiting for permission from Kelsey to release the Ranger class on www.ShadowDarklings.net.  In the meantime, if you'd like to update the Foundry module's character import to include the new Talent bonuses created for Rangers, here they are:

[RangerNewBonuses.txt](https://github.com/Muttley/foundryvtt-shadowdark/files/11378378/RangerNewBonuses.txt)

I believe everything else about the Ranger class should already be supported by your existing import system.

**Comment by bakbakbakbakbak** [comment]
I'll tag this for the version we add support for custom classes. We are not implementing any of the Cursed Scroll classes either, so we'll need to make this a custom class. However, if Kelsey gives full permission to use the Ranger using an appropriate license, then we would implement it into the system.

**Comment by bakbakbakbakbak** [comment]
Implemented in #393
