### ISSUE TITLE
Bug: Talent Sheet touch-ups

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#39]
**Why?**
The Talent Item has quite wonky reactive design as for now, and it most likely breaks due to localization.

**How?**
- The styling (at least) should be reviewed and improved.
- The structure of the generated psuedo-tables is not great right now, adding a new Header to every effect.

**Comment by Muttley** [comment]
Completed a beauty pass over the sheet, it looks a lot better now.
