### ISSUE TITLE
Fighter Talent rounding up instead of down.

### ISSUE THREAD

**Issue by bioxhacker** [Muttley/foundryvtt-shadowdark#423]
once a fighter enter lvl 2+ their weapon mastery is rounding up instead of down.
[lvl 1 normal]
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/75003196/c3fdbd8d-fdd2-479b-a2bd-58c7a20726b7)
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/75003196/b249ddd9-a06c-437c-961a-1e96a5b3ebeb)
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/75003196/8ec3c3c9-03c5-488b-bf2a-cde167105fc7)

[lvl 2]
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/75003196/36331ca8-9a0a-419d-88f0-55803da83ff9)
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/75003196/252da692-2cd2-439a-b2d8-c5e5f9028687)

**Comment by bakbakbakbakbak** [comment]
Sorry I don't get your math here:
The talent says, "You gain +1 to attack and damage with that weapon type. **In addition, add half your level to these rolls (rounds down)**."

So;
Level 1: 
+1 base bonus, +(1/2 = 0.5 ~= 0)  = +1

Level 2:
+1 base bonus, +(2/2 = 1) = +2

Level 3:
+1 base bonus, +(3/2 = 1.5 ~= 1) = +2

et.c.

Just as implemented
