### ISSUE TITLE
Bug: Mage Armor Effect does not change AC

### ISSUE THREAD

**Issue by adotor** [Muttley/foundryvtt-shadowdark#431]
After applying the mage armor effect the AC on the Abilities sheet remains unchanged.

Foundry: 10.291
Shadowdark: 1.3.2
OS: Win 11
Browser: Vivaldi 6.0.2979.22, Foundry Embedded Client

**Comment by shankarnakai** [comment]
Hey
I'm new on developing System on Foundry, but I know javascript.

I will take this bug, ok?

**Comment by bakbakbakbakbak** [comment]
> Hey I'm new on developing System on Foundry, but I know javascript.
> 
> I will take this bug, ok?

sure! Feel free to go with it, just submit a pull request (and don't forget to update the release notes) when you're ready and we'll look at it and see how to get it merged! :)
