### ISSUE TITLE
Shadowdark Character sheet

### ISSUE THREAD

**Issue by teacherx333** [Muttley/foundryvtt-shadowdark#440]
suggestions:
1.  On the background page/tab can you make the class drop down simple fillable.  To allow for custom Class entry.  It appears all this does anyway is turn off the spell tab.  Perhaps a check-box that does the same.
2.  Several custom classes allow for more than one Luck token, would you make the Luck box a single numerical fillable?

**Comment by Muttley** [comment]
> suggestions:
> 
>     1. On the background page/tab can you make the class drop down simple fillable.  To allow for custom Class entry.  It appears all this does anyway is turn off the spell tab.  Perhaps a check-box that does the same.

Customisable classes are planned.  See Issue #374

> 
>     2. Several custom classes allow for more than one Luck token, would you make the Luck box a single numerical fillable?

Issue #343 already covers this

Clossing as duplicates
