### ISSUE TITLE
Feature: Ability to compile in-world, and compendiums for items/spells

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#447]
If we have functionality that can help us find pre-existing items of a certain type, we can have the character builder (and perhaps building the custom classes & ancestries easier) populated with whatever a GM wants to add to the world.

**Comment by Muttley** [comment]
I have something I developed for the John Carter of Mars system I'm slowly working on which will handle this.  It basically builds a deduped cache of specified item types and stores them in the CONFIG object for ease of access.

I can try and get that included ready for when we need to use it.

**Comment by bakbakbakbakbak** [comment]
Awesome, that sounds exactly what the thoughts I had could have crystalized down to!

**Comment by Muttley** [comment]
This has been implemented, see `src/documents/cacheForeignDocuments.mjs`.

**Comment by Muttley** [comment]
Reopening this as lessons learned from the Conan system have revealed that this is not a great way of doing this (too many issues), so will replace with a more dynamic setup.
