### ISSUE TITLE
FEATURE: Bonuses from ShadowDarklings for the Bard class

### ISSUE THREAD

**Issue by MikeMundy** [Muttley/foundryvtt-shadowdark#449]
Hi - I have added support for creating Bard characters on https://www.shadowdarklings.net.

The new Bard Talent bonuses are described in the attached file:
[BardNewBonuses.txt](https://github.com/Muttley/foundryvtt-shadowdark/files/11740722/BardNewBonuses.txt)

Please add support to the Import process for these new bonuses.

**Comment by bakbakbakbakbak** [comment]
This will most likely take a while, as it requires #444 and the dependencies there. But thanks for the data, that will be helpful when we get to implementing the Bard!
