### ISSUE TITLE
Bug: Auto Roll NPC Hit Points is not adding NPC Constitution modifier

### ISSUE THREAD

**Issue by skotothalamos** [Muttley/foundryvtt-shadowdark#450]
When dragging an NPC actor to a scene with the "Auto Roll NPC Hit Points" setting turned on, the system rolls a number of 8-sided dice equal to the level of the NPC and sets the token's hit points and max hit points.

Expected behavior: The system should roll a number of 8-sided dice equal to the level of the NPC, adding the Constitution modifier of the NPC (with a minimum of 1 hit point in the case of a negative modifier).

**Comment by hlmodking** [comment]
This is Evo from discord so you guys know. 
I believe I found the line that needs to be corrected for this. 

`async _npcRollHP(options={}) {
		const data = {
			rollType: "hp",
			actor: this,
		};

		**const parts = [`${this.system.level.value}d8`];**

		options.fastForward = true;
		options.chatMessage = true;

		options.title = game.i18n.localize("SHADOWDARK.dialog.hp_roll.title");
		options.flavor = options.title;
		options.speaker = ChatMessage.getSpeaker({ actor: this });
		options.dialogTemplate = "systems/shadowdark/templates/dialog/roll-dialog.hbs";
		options.chatCardTemplate = "systems/shadowdark/templates/chat/roll-card.hbs";
		options.rollMode = CONST.DICE_ROLL_MODES.PRIVATE;

		const result = await CONFIG.DiceSD.RollDialog(parts, data, options);

		const newHp = Number(result.rolls.main.roll.result);
		this.update({
			"system.attributes.hp.max": newHp,
			"system.attributes.hp.value": newHp,
		});
	}`

I only know one way to fix this and its not the right way, its the brute force way.
Trying to learn so if this helps here is my jank. 

`// Get the dexterity modifier
let dexBonus = this.system.attributes.dex.modifier;

// Ensure that the bonus is at least +1
dexBonus = Math.max(dexBonus, 1);

// Create the dice roll string
const parts = [`${this.system.level.value}d8 + ${dexBonus}`];
`
