### ISSUE TITLE
Missing Move options for NPCs

### ISSUE THREAD

**Issue by git-steve-git** [Muttley/foundryvtt-shadowdark#460]
Looking at the NPC / Monster sheet, in the Move drop down we have Near, Double Near, Triple Near (hi Tarrasque!) and Close.  This covers a lot of monsters, but there are a couple more weird ones that need additional options.

The Archdevil has a move of "far (teleport)", so we need a Far option to cover him.  In theory there may be others down the line.
There are also a couple of other monsters with a move of "none" (rot flower, fungibold mage.)

Might be a wise idea to also add a "Special" option, just to cover our bases for any weirdo monsters that move in especially strange ways that require special rules to describe.  I don't know if any such monsters already exist, but you never know right?

**Comment by bakbakbakbakbak** [comment]
I'm tagging this as an enhancement (for now), because I think the suggested `Special` move is a good way to do this, and that would require some modification of the NPC sheets.
