### ISSUE TITLE
Monsters lacking attack bonus's

### ISSUE THREAD

**Issue by teacherx333** [Muttley/foundryvtt-shadowdark#476]
I am using v11 and none of the creatures have attack bonus's.  Apparently my friends who have yet moved to v11 have them.

Evounnamed has witness my issue on discord.  Images are there in discord.

**Comment by Arthil11** [comment]
This is still an ongoing issue. Been over a month since it was reported on... Kinda hope it gets fixed before another month is out.

**Comment by anders-tech** [comment]
@Arthil11 I have the same issue, but you can just add the bonus back in yourself as a workaround.

**Comment by Muttley** [comment]
Please can you provide specific examples, along with screenshots here.  Unable to replicate this issue.

**Comment by teacherx333** [comment]
Sorry, I hope this helps.

**Comment by teacherx333** [comment]
I have to send this again files too big.

**Comment by teacherx333** [comment]
Part 2 of Pics

**Comment by teacherx333** [comment]
Sure, here it is.  the attack bonuses and damage bonuses listed in the
descriptions are not the the "Attacks" portion of the "Abilities" page

**Comment by Muttley** [comment]
Looks like the Monster compendium wasn't run through the Updated_230418_1 and then re-exported.

I'll fix this up when I tidy up the compendiums before starting work on the next release.

**Comment by teacherx333** [comment]
roger doger

**Comment by teacherx333** [comment]
Awesome, thanks for the update!
