### ISSUE TITLE
Request - GM only viewable page on items

### ISSUE THREAD

**Issue by teacherx333** [Muttley/foundryvtt-shadowdark#477]
I wish to request a GM only viewable page on items.  In order to place curses hidden from players.  i don't believe the curses/side effects should be viewable to players just because.

It will be easy to then copy this curse into the general description once the player discovers the curse.

Thank you

**Comment by bakbakbakbakbak** [comment]
This is already built in into the editor in Foundry if you use the "Secret" text-type:
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/105067023/f87c4467-4f88-456d-865f-7e5584d623cb)

And as seen by one of the players:
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/105067023/5027a14b-b9ff-4441-9f1d-6b35abe5ee7e)

Caveat: This only works if the player is **not** the owner of the item as they can go in into the description and edit it, seeing the secret. But if you are building items for your players already, having them as "Observers" on the items should be sufficient for them to interact with them.

**Comment by teacherx333** [comment]
Man a private email, this is unexpected and a welcomed answer.  I never
hovered over that button and I would not have thought to.
Thank you so much!!

You Da'bomb.  Oops do they still say that, crap dated myself again.

**Comment by teacherx333** [comment]
As GM and owner, I always see the secret text correct?  I have to log on as
a player to NOT see the text?

**Comment by teacherx333** [comment]
I can't get it to work, sorry do you have step by step instructions.  my
secret info is not shaded or inside the lines, but the button highlights.

**Comment by teacherx333** [comment]
OK so, panic mode is over.  Ironheart instructed me, and now I know how to
work the magic.

**Comment by bakbakbakbakbak** [comment]
Alright, so I'm closing the issue now as it seems you have gotten it to work :)

**Comment by teacherx333** [comment]
yes thank you so much
