### ISSUE TITLE
Bug: Melee Damage bonus from talents/ancestries are incorrectly being applied to thrown weapon damage.

### ISSUE THREAD

**Issue by DM-BenC** [Muttley/foundryvtt-shadowdark#478]
Melee Damage bonus from talents/ancestries are incorrectly being applied to thrown weapon damage.

Example: If you have a Half-Orc Fighter who has the +1 melee attack and damage bonus talent and ancestry option from 'mighty' then their damage bonus of +2 should not be applied to their damage with a thrown dagger - but it is at the moment (or at least it is for me).

**Comment by Muttley** [comment]
The dagger has the Finesse quality, which means you can use either your Strength or Dexterity when attacking with it (Quickstart p.35), so we always use the highest bonus of the two.
