### ISSUE TITLE
Nice-to-Have: Boons as a category (maybe under the Talents tab?)

### ISSUE THREAD

**Issue by git-steve-git** [Muttley/foundryvtt-shadowdark#479]
So, I've been looking at boons (pg 280 of the SD core book), which are essentially non-physical treasures.  Blessings, Oaths and Secrets.

I was thinking it would be nice to have these things noted somewhere on the character sheet so that people remember they got them, but the Inventory tab (where actual Treasures go) doesn't really seem the right place since they're not physical things and they don't take up space.  Also, since at least some of the examples seem like specific, repeatable things (Like "Wraithsight: See invisible and hidden creatures") it might be nice to have them as an item so we can drag and drop on multiple people or whatever, rather than repeatedly typing them out in Description every time someone rolls a specific blessing on a table.

The Talent item cards seem perfect for the purpose or recording them, all we really need is a category for Boons to put them in on the Talent tab.

**Comment by Muttley** [comment]
Related ticket #499
