### ISSUE TITLE
Ability to create custom weapon and armor properties

### ISSUE THREAD

**Issue by git-steve-git** [Muttley/foundryvtt-shadowdark#480]
Whether for Homebrew or to accomodate new properties in the Cursed Scroll zines, it would be nice if users could define their own custom properties to put on weapons and armor.  No mechanical support is necessary, just the ability to add more things to the list of selectable options.

**Comment by bakbakbakbakbak** [comment]
I guess this could be jacked in with the work we do on custom classes and extensions of the CONFIG, right @Muttley ?
