### ISSUE TITLE
Bug: Spell Advantage talent not functioning

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#485]
The talent "Spell Advantage" is not functional, the following issues are observed:

1. The check on Row 260 in PlayerSheetSD.mjs is containing a typo
2. When importing a spell even after fixing typo in 1, it modifies the talent inside the compendium, so if multiple spell advantages are added, the system won't prompt the user for what spell to pick.

I suggest we rework the Spell Advantage check somehow. It uses `system.bonuses.advantage` as effect key, and the "REPLACEME" check, this is not a great solution. I think adding a new bonus called `spellAdvantages` and combine the `system.bonuses.advantage` & `system.bonuses.spellAdvantages` lists would be a better suited way.

**Comment by Muttley** [comment]
Appears to be working as-is:
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/853835/6cb858b1-76af-4536-9d4d-9be85f12540e)

Can you confirm this is still an issue?

**Comment by TheBrianFactor** [comment]
What should be the "Effect Value" when replacing the REPLACEME?  I am not prompted when I add the talent to a character sheet that already has spells learned.

**Comment by Muttley** [comment]
> What should be the "Effect Value" when replacing the REPLACEME? I am not prompted when I add the talent to a character sheet that already has spells learned.

It should be the slugified version of the spell name, you can look at the Magic Missile Advantage talent for an example, and you can get foundry to show you what that should be by opening the console and typing:

```javascript
"<Spell Name>".slugify()
```

Just replace `<Spell Name>` with the full name of the spell.

**Comment by TheBrianFactor** [comment]
> > What should be the "Effect Value" when replacing the REPLACEME? I am not prompted when I add the talent to a character sheet that already has spells learned.
> 
> It should be the slugified version of the spell name, you can look at the Magic Missile Advantage talent for an example, and you can get foundry to show you what that should be by opening the console and typing:
> 
> ```js
> "<Spell Name>".slugify()
> ```
> 
> Just replace `<Spell Name>` with the full name of the spell.

Using the slugify worked like a charm, thanks!

I still, however, am not prompted to select a spell when I drag "Spellcasting Advantage" to a character sheet with existing spells.
