### ISSUE TITLE
Incorrect details in Lost Citadel

### ISSUE THREAD

**Issue by Boi10217** [Muttley/foundryvtt-shadowdark#488]
1. entrance by room 10 didn't have a light source from outside.
2. missing monster tokens for the ochre jelly in room 20 and the animated armor in room 26.
2. the southern two doors in room 18 were marked as locked rather than open.

**Comment by bakbakbakbakbak** [comment]
1. There is no description of a light source in room 10 in the quick start guide.
2. Room 26 have no animated armor. 
3. The bottom left door is supposed to be locked.

That leaves a missing Ochre Jelly in room 20 and perhaps the bottom right door in room 18 being locked while it shouldn't.
