### ISSUE TITLE
Hauler - Fighter Carrying Capacity not adjusting

### ISSUE THREAD

**Issue by TheBrianFactor** [Muttley/foundryvtt-shadowdark#492]
Fighter class:
"Hauler.  Add your Constitution modifier, if positive, to your gear slots."

This is not being applied on character sheets when a PC selects "Fighter" as their class.

**Comment by Muttley** [comment]
Have you added the Fighter class talent "Hauler" onto the character sheet?

**Comment by TheBrianFactor** [comment]
> Have you added the Fighter class talent "Hauler" onto the character sheet?

I had not.  When I do that, though, it resolves the issue.  Thank you.

**Comment by Muttley** [comment]
No problem, glad you got it working
