### ISSUE TITLE
Compendium Not Merging With Updates

### ISSUE THREAD

**Issue by TheBrianFactor** [Muttley/foundryvtt-shadowdark#534]
For every update I have had to recreate the custom classes because they do not carry over to the newest update.  I've had to create the Knight of St. Ydris, Witch, and Warlock three times now.

The class options remain in my items, but they cannot be opened because the compendium entries are deleted.

**Comment by PrototypeESBU** [comment]
The default shadowdark compendiums will be replaced entirely on new updates. This is normal behavior. All custom classes should be stored in a separate world level or shared level compendium for this reason.

**Comment by TheBrianFactor** [comment]
> The default shadowdark compendiums will be replaced entirely on new updates. This is normal behavior. All custom classes should be stored in a separate world level or shared level compendium for this reason.

Any guidance, or a how-to link on how to make sure I do this appropriately?

**Comment by PrototypeESBU** [comment]
Just create a new world level compendium outside of the _shadowdark default_ and _shadowdark system_ folders in the compendium tab. See this article for more details. https://foundryvtt.com/article/compendium/
It's helpful to look at the icons that appear on the compendium in the tab:
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/147362581/0b2bdf52-498b-480e-b586-b627a592f2cb)

As a best practice, avoid modifying system or module compendiums as they might be overridden by updates.

**Comment by TheBrianFactor** [comment]
That's very helpful, thank you!  I'm working on porting all of the system compendium to a world compendium before I update to the latest version.
