### ISSUE TITLE
Bug: Bloodlust magical Item breaks character sheet

### ISSUE THREAD

**Issue by esandvik** [Muttley/foundryvtt-shadowdark#535]
Steps to reproduce: Create test Player Actor, Add Bloodlust weapon from the Magic Items Compendium, Try to equip, error will appear in console, close character sheet.  Can no longer open sheet.  

If you delete item prior to closing the sheet, sheet works properly.

Suspect its due to active effects referencing system.bonuses.attackBonus and system.bonuses.damageBonus rather than meleeAttackBonus and meleeDamageBonus as they do not exist when looking at Player Attributes

However given the fact that there are abilities that add damage to all sources it may be better to add the generic attack and damage bonus attributes.

**Comment by PrototypeESBU** [comment]
It looks like it's because that item has a property that isn't mapping over correctly.
