### ISSUE TITLE
Ranger D12 damage seeming to roll twice and take the lowest

### ISSUE THREAD

**Issue by Delgored** [Muttley/foundryvtt-shadowdark#537]
I'm experiencing the ranger's D12 damage ability rolling at disadvantage.

Is it supposed to do this?

**Comment by Muttley** [comment]
You'll need to be more specific with example screenshots.  What do you mean it's rolling at disadvantage?  We don't have any code which automatically rolls advantage or disadvantage

**Comment by Delgored** [comment]
The screenshots below show two D12s being rolled.

This one it took the lower of the damage rolls for the longbow
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/148171166/1dca0211-c374-45d6-9a1d-81d3e5f630a1)

This one took the higher
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/148171166/2f5e4f05-68ca-46dd-b789-398944fc5e66)

I've made another Ranger with a dagger as the special weapon and it does the same thing.

Could it just be rolling another animation?

**Comment by Delgored** [comment]
Here's the guy with the dagger.   I put a dialog box up to show the settings for the roll

![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/148171166/ae1aff5f-2538-49ab-ae42-285c48adb101)

For the characters I used the importer from ShadowDarkling in JSON format.

Thanks,

**Comment by Muttley** [comment]
Found the issue.

The good news is that this is purely a cosmetic issue and the values reported to the chat are correct.

A fix for this will be in the next release.
