### ISSUE TITLE
Magic Armor items appearing in Class proficiency list

### ISSUE THREAD

**Issue by git-steve-git** [Muttley/foundryvtt-shadowdark#548]
For some reason, all of my individual magic armors (ie: Armor of St. Tarragnis, Moonwrought Chainmail, etc) are appearing in the armor proficiency drop down on the Class Item.  This does not seem to happen with magic weapons in the weapon proficiency drop down, however.

Expected: Only "base armors" should appear - Chainmail, Plate Mail, etc but not individual magic armor pieces.

**Comment by Muttley** [comment]
Could you export one of the problem items and attach it to the ticket so I can test?
