### ISSUE TITLE
Feature: Allow custom Talents for classes

### ISSUE THREAD

**Issue by sjmiller85** [Muttley/foundryvtt-shadowdark#553]
As it stands right now, if I create a custom class (e.g. the Witch from the 1st zine), I can't set the class's talents without editing the standard Talents compendium pack.  If I edit that list, I presume it's going to be overwritten back to the default list as soon as I pull a new release, losing all my work.  If I create a custom Talents compendium, the character sheets can't recognize them because (I'm assuming), they're only looking in the default Talents compendium pack.  It'd be nice if there was a way to create custom talents and be able to add them to custom classes without fear of losing all our work when we update to a new version.

**Comment by sjmiller85** [comment]
Disregard, my browser must have been caching parts of my outdated pull of SD.  I believe I've found a way to

**Comment by Muttley** [comment]
For reference, new talents you create need to be in a compendium (your own, not the system ones) to be picked up by the system.
