### ISSUE TITLE
Hide auto-roll NPC Hit Points

### ISSUE THREAD

**Issue by stickas** [Muttley/foundryvtt-shadowdark#561]
When you add an NPC with the auto roll option available, the outcome of the roll is not shown in the chat but the dice are not hidden. This is using the Dice so Nice mod as well.

**Comment by PrototypeESBU** [comment]
@stickas a few thoughts: 
- Dice so Nice can, on rare occasion, shows different results that the actual role, so I think a roll to chat makes sense.
- The HP rolls will respect your default roll option, so as long as that isn't set to public it won't be shown to players.

I think that blocking these rolls from showing up by default might get in the way of GMs wanting them shown publicly. Maybe the enchantment could be to add a setting to force these rolls to be done under "Self Roll" for all occasions. Something like "hide npc hit roles form players". 

Thoughts?

**Comment by stickas** [comment]
I didn't mention it. I always roll hidden for these things, but I did try all the options with no success. Player saw all the rolls of the dice.
Since there is already an option to auto roll npc hp when they are added to scene, there could be also another underneath for hide/show maybe.

**Comment by Muttley** [comment]
Currently NPC hit point rolls are hard-coded to be GM Rolls, regardless of chat setting.

The secondary issue is that we currently don't pass the relevent roll mode information to Dice So Nice! so it can determine whether to show the dice or not.  Fixing this will need some changes to how RollSD works.

**Comment by Muttley** [comment]
Found the ticket #362 so closing this as duplicate
