### ISSUE TITLE
Funny UI Behaviour with Light Tracker

### ISSUE THREAD

**Issue by git-steve-git** [Muttley/foundryvtt-shadowdark#57]
So I just pulled down the newest code, recompiled via gulp and put it into my systems directory.
When I launch the game world, the Light Tracker pop up is front and center.  Everything looks OK.

![before](https://user-images.githubusercontent.com/46088451/226135111-bd8fbc4f-10f1-42e7-a230-09d8ae27435f.png)

When I click "Turn off the lights" it causes the bottom part of the UI to jump up to about half-way down the screen (just below the last button on the left button list), where it remains even after refreshing with F5.  (It seems to be related to the content in the right sidebar - a lengthy chat log will push the lower elements back towards the bottom of the screen, but it will jump back up for tabs that have less content.)

![after](https://user-images.githubusercontent.com/46088451/226135065-0dade7e5-86cb-4b2f-ad36-37b4ad957ecd.png)

The same issue occurs with a new world.
~I took screenshot but I can't figure out how to upload them.~

**Comment by bakbakbakbakbak** [comment]
I think you can only press Ctrl+V if you have it in clipboard and it will upload the screenshot automatically!

**Comment by git-steve-git** [comment]
Thanks, that worked for adding screenshots!

**Comment by Muttley** [comment]
Feature was incomplete.  Issue is not there now.
