### ISSUE TITLE
Shadowdarklings Import Pulls from System Compendium

### ISSUE THREAD

**Issue by TheBrianFactor** [Muttley/foundryvtt-shadowdark#576]
When I use Shadowdarklings to import a character, the Ancestry, Class, Background, Deity, etc. fields pull from the system compendium instead of the user compendium.  Is there any way to fix this so it defaults to the appropriate user compendium?

**Comment by Muttley** [comment]
It doesn't actually.  It will use them from *any* compendiums.  But they need to be proper compediums, not just folders in the Items section.  Also, if you're duplicating the core classes for some reason, it's likely that it will pick the first matching class it comes across.

If you have specific examples of issues, then please give more details and attach your custom compendium so we can test.

**Comment by TheBrianFactor** [comment]
I have copied the core classes and every other core compendium so I could/can tweak some formatting to suit my eyes/brain better...particularly the **Description** section of the classes.  Below is how I've formatted the Priest class in my user compendium:
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/45749331/b8fb698a-bbe2-424d-bdde-39fedd3f1843)
Each class has a linked critical failure journal entry or rollable table as applicable, respective spell progression tables, and linked spell tier list journals.

However, when I created a new NPC with the Priest class, it pulled the system compendium:
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/45749331/991b285e-b848-4c14-8f33-349109d0fd96)

I have, for now, named my user/world compendium as Ancestries (Copy), Backgrounds (Copy), etc. as the default naming system.  Is there a way to supercede that so new characters pull from my user/world compendium (either by naming or other methods)?

I'd also be happy to share my custom compendium, but I'm unfamiliar with how to do that...I'm more of a organization person and don't really know a lick of coding :(

**Comment by Muttley** [comment]
> I have, for now, named my user/world compendium as Ancestries (Copy), Backgrounds (Copy), etc. as the default naming system. Is there a way to supercede that so new characters pull from my user/world compendium (either by naming or other methods)?

That won't do anything as it looks for the item types, not the names of the compendiums.

There won't be a way of disabling the core items until we get round to doing the built in character creator I'm afraid.

> I'd also be happy to share my custom compendium, but I'm unfamiliar with how to do that...I'm more of a organization person and don't really know a lick of coding :(

We can certainly looks at making requested changes to Item descriptions if they're relevant.  Easiest way to share your compendium is to create an empty world with them imported and back that up (the internal Foundry backup tool will be fine) and attach it to this ticket for us to look at.

**Comment by TheBrianFactor** [comment]
Got ya, so at present there's no way to toggle system items off.  Would a bypass/workaround be to go to each default item that I have adjusted and rename it?  E.g. the Priest class, rename the default Priest class item "xPriest"?  As an aside, I have manually input the Cursed Scroll classes (from all 3 Cursed Scrolls) and they work flawlessly with Shadowdarkling import (Knight of St. Ydris, Warlock, and Witch tested so far).  I don't know if that feedback is helpful or not but I figured I'd share.

I think the item descriptions for classes would do well with additional information - my intent for my personal game is to minimize how often players and the DM (me) need to tab back-and-forth to reference the PDF rulebook.  I know this ultimately comes down to licensing concerns with the ability to include the information, but I believe the relevant information is important for class item descriptions:

1. Link to rollable table for class's talent table.  This should also extend to additional tables like the Patron Boon rollable table for Warlock.
2. Link to critical failure relevant rollable table or journal entry for spellcasting classes.  Priest = Priest Penance; Wizard = Wizard Mishap; Witch and Knight of St. Ydris = Diabolical Mishaps, etc.
4. Link to entire spell list for class.  I have done this in a journal entry.  Said journal entry also links to every single spell's Spell Item for quick reference when spells can be learned or if a player would like to reference a spell's text quickly (especially for spells they do not currently know).
5. *Optional* I've gone as far as including spell breakdown for each caster class by spell Tier to make the list reference quick when learning a new spell due to leveling rewards.

Martial Class Item Description example:
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/45749331/a552d629-96d6-452c-a040-3e5d940306bd)

Spellcasting Class Item Description example:
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/45749331/5d2756ae-cf35-4ef9-9574-15fd234d9be7)
Each class links to "Level Progression: <Class> which has the level advancement table from p. 39 of the rulebook.  The Warlock level advancement also links to a journal entry containing all of the Patron Boon tables so it's universal for all Warlocks, regardless of their Patron.
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/45749331/4f523da1-4baa-416c-bed2-db19413627a6)

Honestly, that last bit about me sharing my compendia went over my head, so I've not attached anything.

**Comment by Muttley** [comment]
> Got ya, so at present there's no way to toggle system items off. Would a bypass/workaround be to go to each default item that I have adjusted and rename it?

No, that probably wouldn't work.  You'll just have to make do with the built in classes until we make the required changes.

We also can't add anything that isn't in the quickstart, as that's the agreement we have with Kelsey.

**Comment by TheBrianFactor** [comment]
All understood :).  I'll just use my current method, no biggie :)

**Comment by Muttley** [comment]
Issue #631 tracks the ability to filter out compendiums.  Will close this issue.
