### ISSUE TITLE
UI Improvement: Standardize spellcasting iconography

### ISSUE THREAD

**Issue by chrpow** [Muttley/foundryvtt-shadowdark#578]
Currently, when a spell is dragged onto a character sheet, four options are given: Potion, Scroll, Spell, and Wand, each with their own icon:
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/15185224/43d5ee1d-5e3f-4fb3-8eeb-85006999b3f1)

Once the spell has been added to the character, it is also accompanied by an icon. The Potion and Scroll icons are consistent between menus, but the wand changes appearance (it now has sparkles) and is used for both wands and known spells:
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/15185224/cb4a0fb9-b0f7-485e-8f87-93202b58c49f)

I propose using a single wand icon \<i class="fa-solid fa-wand-magic-sparkles"></i> for all wand related actions, and using a single spell icon (I personally think \<i class="fa-solid fa-sparkles"></i> is very clear and visible) for spells cast from the character's known spells list.

**Comment by Muttley** [comment]
Unfortunately we can't use fa-sparkles as it's part of the Fontawesome Pro set which would mean we would need to buy a license.

If you can find an alternative from the free fontawesome collection we can certainly consider that.
