### ISSUE TITLE
Feature: Support optional "clockwise" initiative

### ISSUE THREAD

**Issue by chrpow** [Muttley/foundryvtt-shadowdark#590]
Since RAW Shadowdark is played in a fixed turn order once the highest initiative has been rolled, it would help to be able to quickly drag characters in the initiative to rearrange them on the fly. The Pathfinder 2E Foundry system has this capability, so I will start looking there to see how it was implemented.

**Comment by chrpow** [comment]
I started work on this, got distracted, and ended up just implementing the "clockwise" initiative. Once I get it looking nice, I'll submit a pull request for a global option that switches the game between "clockwise" initiative and the traditional, "everyone rolls" initiative.

**Comment by Muttley** [comment]
How do you determine "clockwise" when there is no positional information to work with?

**Comment by chrpow** [comment]
Im basing it on the order of game.users.players. I guess "clockwise" is a misnomer, but the point is that the initiative sequence will always remain the same even across encounters, and all GM controlled tokens will go at the same time.
