### ISSUE TITLE
Ranged weapons missing backstab box on characters with the backstab talent on sheet.

### ISSUE THREAD

**Issue by teacherx333** [Muttley/foundryvtt-shadowdark#610]
Backstab box is missing on ranged weapons.  The backstab box appears for melee weapons and melee weapons that can be thrown, but on "Ranged" weapons it is missing, only used core weapons when determining this.

**Comment by PrototypeESBU** [comment]
Related to this line:
https://github.com/Muttley/foundryvtt-shadowdark/blob/118a4d66d4196bce0653c0a614b1e54611baebe0/system/src/documents/ActorSD.mjs#L1004
