### ISSUE TITLE
1.6 Monster Importer does not properly parse monster spells when copied directly from PDF without formatting.

### ISSUE THREAD

**Issue by chrpow** [Muttley/foundryvtt-shadowdark#615]
I've tried importing text directly copied from the rulebook PDF on two monsters with spells, and experienced two different issues.

Acolyte: throws an error, does not import spell or features:
Failed to fully parse the monster stat block. TypeError: Cannot read properties of null (reading '1')
f
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/15185224/fcd9dc72-1bfe-482e-be88-5ebc3277a88b)

Archmage: does not throw an error, but imports all spells as one spell.
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/15185224/68f72bd7-bba3-4a1b-add5-3f6abc33cb25)

These can be made to work by playing with the spacing in the text box, but I don't think this should be necessary since the monster importer was previously able to import monsters directly copied from the PDF.

**Comment by PrototypeESBU** [comment]
I'm not able to replicate either error. What PDF viewer are you using? I tested/developed with both Adobe and Foxit.
For the Acolyte, are you able to link a base64 encoded string of your clipboard data?  https://www.base64encode.org/
For the Archmage, as always you will need to put in a blank newline between all the spells, features or abilities, but you shouldn't need to worry about the trailing newlines.

**Comment by PrototypeESBU** [comment]
I was able to reproduce the Acolyte error by adding extra newlines at the end of the text block. If you backspace all the way to the "1d4 HP." does it work then?

**Comment by PrototypeESBU** [comment]
@chrpow is this still an issue?

**Comment by chrpow** [comment]
@PrototypeESBU this can probably be closed. Thinking about the utility of the monster importer, there's no reason it has to work 100% automatically if you only import each monster once. Spending effort accommodating every possible input format is probably a waste of time.
