### ISSUE TITLE
1.6 Monster Importer's parsing of spell ranges is not very robust

### ISSUE THREAD

**Issue by chrpow** [Muttley/foundryvtt-shadowdark#616]
The monster importer is able to interpret spell ranges from the description in some cases, but not all.
```
		// Take a chance at finding the range in the description
		if (descStr.includes(" self.")) {
			spellObj.system.range = "self";
		}
		else if (descStr.includes(" close.")) {
			spellObj.system.range = "close";
		}
		else if (descStr.includes(" near ") || descStr.includes(" near.") || descStr.includes(" near-sized ")) {
			spellObj.system.range = "near";
		}
		else if (descStr.includes(" far ") || descStr.includes(" far.")) {
			spellObj.system.range = "far";
		}
```
The SD texts are inconsistent about whether to use periods or commas in the range description. This block of text could use a few more cases to include all possibilities. I will try to find cases that cover all the published monsters adequately.

**Comment by PrototypeESBU** [comment]
Yeah, these statements are low effort tries for the range. Would welcome approves, but you're right that there's isn't a strong convention for this, even within the core rules.
