### ISSUE TITLE
Show a notification error if no token selected when using hotbar items

### ISSUE THREAD

**Issue by Muttley** [Muttley/foundryvtt-shadowdark#620]
Upon dragging items from the inventory page of a character sheet to the hotbar, and then clicking on any of the items, A Foundry error appears, reading "No such item found on character."

I didn't realize that I had to select a character's token first.  Could the Foundry error be amended to clarify that detail for future GM's and players?

_Originally posted by @sjmiller85 in https://github.com/Muttley/foundryvtt-shadowdark/issues/220#issuecomment-1828905904_

**Comment by PrototypeESBU** [comment]
You only have to select a character token only if there is no character selected for that player. A preferred mode of operation is to assign a character to the player. Will look at update the error message to provide more clarity.
