### ISSUE TITLE
1.6 Monster importer fails to import some monsters with 1 damage attacks (1 + [special attack])

### ISSUE THREAD

**Issue by chrpow** [Muttley/foundryvtt-shadowdark#622]
I'm sorry for making three separate issues about the monster importer, but as far as I can tell they're unrelated, and I'm investigating them separately.

I did a mass import of the core rulebook, and the following monsters threw errors via the monster importer:

- Fairy
- Jellyfish
- Rat, Swarm
- Rat
- Scorpion
- Snake
- Spider

All of these throw this error:
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/15185224/774dd7f2-4d63-4a9f-9e47-19d60004368d)
Even when copied and pasted manually, formatted correctly.

I've attached a .txt containing the exact text that was entered into the monster importer.
[core rulebook problem monsters.txt](https://github.com/Muttley/foundryvtt-shadowdark/files/13608491/core.rulebook.problem.monsters.txt)

From this I determined that the problem is the phrasing of "(1 + [special attack])" in the monsters' stat blocks. The monster importer should be updated to parse this syntax correctly.

**Comment by chrpow** [comment]
I've found another case that isn't accounted for yet:
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/15185224/0d02cb40-dec8-448f-8dbc-b7484cffa819)
The Heal Cube doesn't deal any damage at all, and therefore can't pass the current monster importer.

**Comment by PrototypeESBU** [comment]
Changes successfully merged
