### ISSUE TITLE
Unintended attribute name for actor's hp in data structure?

### ISSUE THREAD

**Issue by JBryskiewicz** [Muttley/foundryvtt-shadowdark#627]
It is rather minor issue and most likely just a small naming mistake. I just noticed that base hp refers to max hp, but max hp attribute does not? I simply cannot find what hp.max is used for in such case.
If this structure was intended tho, I will close the issue report, cheers.

![shadowdarkRPG_hp_attribute_max](https://github.com/Muttley/foundryvtt-shadowdark/assets/105501793/9e54a076-bfa2-4393-b2d1-40e18fdd4fc4)

**Comment by Muttley** [comment]
This is intended.
