### ISSUE TITLE
Magic Item Effects Seeming to Not Transfer to Character

### ISSUE THREAD

**Issue by TheBrianFactor** [Muttley/foundryvtt-shadowdark#628]
One of my players received a Moonwrought Chainmail for their character in session today.  The item provides the ability to choose to add +1 to spellcasting or +1 to ranged attacks once per day  (see below):
![Moonwrought Chainmail](https://github.com/Muttley/foundryvtt-shadowdark/assets/45749331/f2967596-c787-4859-87aa-d6f0c2056542)

I have edited the magic item to have effects to represent the +1 Spellcasting choice and the +1 Ranged Attack choice.  The first roll demonstrates a standard choice when both effects are toggled as "inactive" (the PC's bonus to spellcasting is +3, innately).
![Moonwrought Chainmail, effects off](https://github.com/Muttley/foundryvtt-shadowdark/assets/45749331/7e757b93-4b89-4208-936a-d1dd2c0b286f)

The second roll demonstrates a roll where the PC chose to use the +1 Spellcasting option.  However, the roll is not augmented by the +1 Spellcasting being set as "active" (the PC's bonus to spellcasting is +3, innately, and should gain an additional +1, totaling +4).
![Moonwrought Chainmail, effects on](https://github.com/Muttley/foundryvtt-shadowdark/assets/45749331/88f84daf-bd71-406f-a01a-abacc63bc86c)

Am I misusing/misunderstanding how to use this active/inactive function?  Is this a bug?

**Comment by Muttley** [comment]
Did you add the effects *before* it was added to the character?  Foundry is a bit weird with not picking up new effects if you add them afterwards.

**Comment by TheBrianFactor** [comment]
Yes, I added the effects before adding the item to the PC inventory.  I even deleted the item, made sure the effects were present on the item, toggled them to inactive, _then_ moved the item to the PC inventory.  Same issue.  Additionally, this happens when the game is paused and unpaused, the +1 Spellcasting and +1 Ranged Attack both fail to apply, and it does not matter if there is an effect duration added or not added.

**Comment by Muttley** [comment]
I'm totally unable to replicate this.  You you provide a JSON export of the item in question and attach it to this issue, so I can test with your exact item.

**Comment by TheBrianFactor** [comment]
Here you go, thanks, as always, for the help.
[fvtt-Item-moonwrought-chainmail-(mithral)-iEsEFLhvb7six27y.json](https://github.com/Muttley/foundryvtt-shadowdark/files/13693649/fvtt-Item-moonwrought-chainmail-.mithral.-iEsEFLhvb7six27y.json)

**Comment by Muttley** [comment]
Ah, I think I can see what the problem is here (it's a twofold thing) now I've .

First you have the effects set up as "turns" .  Until v1.7.1 released yesterday we didn't even support turns (a turn lasts 10 minutes real time).

Also, you can't really create these kind of timed effects on the item itself, they need to be created on Effects items which can then be dragged to the character when needed.  Easiest way is to put a shortcut to the Effect item in the item's description so that the player can just drag the effect onto their sheet themselves when they use the effect.

**Comment by TheBrianFactor** [comment]
Okay, I follow you.  I was likely trying to create/establish the item like 5e system.

Is there a way to implement that (and other) Effect items as a macro?  Select the token, click the macro, it applies Effect 1 or Effect 2 depending on the macro used?

**Comment by Muttley** [comment]
> Okay, I follow you. I was likely trying to create/establish the item like 5e system.
> 
> Is there a way to implement that (and other) Effect items as a macro? Select the token, click the macro, it applies Effect 1 or Effect 2 depending on the macro used?

There's nothing in the system to do that kind of thing, it would be fairly trivial to create a couple of items and then write some custom macros to add those items to a character.

This is not something we're likely to add to the system though.  Plenty of macro writing documentation here though: https://foundryvtt.com/article/macros/
