### ISSUE TITLE
Source Filtering Doesn't Seem to Fully Filter Excluded System sources

### ISSUE THREAD

**Issue by git-steve-git** [Muttley/foundryvtt-shadowdark#649]
It would appear, at least for content that exists in the system compendia, if I duplicate that content to move it to a module (where I can edit it to my heart's content) and then try to exclude the system's sources from being used, the drop downs will still pull from the system compendia if I fully delete a copied item in my module.
 
For example, with Languages, here's what I did:
1. set up my own module-specific source for content I intend to keep in my shared compendium, following the format shown in the latest release.
2. launch my SD world, go to settings for the system.
3. Select my own module-specific source as the only one to be included.  UI says it will only take content from the selected source.
4. Go to Shadowdark compendiums and import all the Languages into the world
5. Edit all the languages to change the source to my own module-specific source.
6. Export all the languages out to my personal shared compendium, delete them from the world.
7. Later on, I deleted the "Elvish" and "Goblin" languages from my shared compendium, for reasons.
8. When migrating the Dwarf ancestry in similar fashion, I had to update all the languages to match my module source.
9. With the languages drop down open, I still see Elvish and Goblin in the list, even though the only allowed source is my module source and those languages no longer exist in my module.
10. When I select either of those two languages and check the Source tab, it says "Shadowdark: Quickstart Set" (ie: the system source.)
11. The rest of the languages besides the two I deleted are properly linking to my module versions.
12. If I delete the system versions of those languages, they disappear form the drop down in the Ancestry tile.

So it seems like I can redirect content to my own module as long as I don't delete it.  System content will keep appearing even when the system sources are excluded in settings, if there is no copy of that content in my module source.

**Comment by Muttley** [comment]
Currently the filtering only applies to selectors on the character sheet.

Can I ask why you're trying to duplicate core items?

**Comment by git-steve-git** [comment]
Because I want to edit them and insert a bunch of flavour unique to my campaign world in the descriptions and so on, which happens to include deleting some of them (Elves speak Sylvan, for example) and renaming others.  I don't want these changes to be erased on a system update, so I'm making my own copies.

Even if I make all my campaign-specific languages from scratch, I still want to filter out the core system ones, which is the main problem I'm having here.  Core sources are still showing up even though they are not selected in the new filter setting.

**Comment by Muttley** [comment]
> Because I want to edit them and insert a bunch of flavour unique to my campaign world in the descriptions and so on, which happens to include deleting some of them (Elves speak Sylvan, for example, so there's no separate "Elvish" language) and renaming others. I don't want these changes to be erased on a system update, so I'm making my own copies.
> 
> Even if I make all my campaign-specific languages from scratch, I still want to filter out the core system ones, which is the main problem I'm having here. Core sources are still showing up even though they are not selected in the new filter setting.

I mean, this is doable from a coding point of view, but it does raise problems.

For example, in order to completely disable the quickstart materials in *all* selectiors you would have to duplicate almost every item type, including Armor, Weapons, Properties, Ancestries, Backgrounds, Class Abilities, Classes, Deities, Languages and Talents.  Basically anything that is pulled from the compendiums in a drop down.

That's a lot of work compared to just naming them slightly differently so they are easily distinguishable...

**Comment by git-steve-git** [comment]
If you're not willing to address the issue, I understand, but the issue is about what sources show up in the dropdowns, not what I am or am not creating in my own source.

If I filter only for items from source X, Y and Z, I don't expect to see items from source A appear when I'm making a new ancestry.  The fact that source A is core is irrelevant.

Maybe I want to use Shadowdark to run a sci-fi game using Star Trek races.  I still want to filter out Dwarvish and Elvish even if I'm creating new languages to match the Star Trek races.  The fact that I can more easily tell them apart from the language items I created does not change the fact that they're cluttering up the drop down list with things I was trying to exclude.
