### ISSUE TITLE
New System Default: unlinked initiative

### ISSUE THREAD

**Issue by gatesvp** [Muttley/foundryvtt-shadowdark#659]
In Shadowdark, initiative is not necessarily connected to combat, it's a global game value. It continues across scenes and only resets when a combat is initiated.

 - Foundry supports feature this via the "unlinked initiative tracker". ![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/319590/234db167-aac5-4864-8466-6c1c8ed4876b)
 - That feature is off on by default, but the rules of SD suggest that "on" is the correct value
 - Because this is a change from the default, we include this in the tutorial

### Current Behaviour

New SD Worlds have "linked" initiative.

### Expected Behaviour

1. New SD Worlds default the "unlinked" initiative.
2. The SD Tutorial mentions this quirk and shows how to turn it off

### Notes

Initially proposed by Evounnamed in the [Discord channel](https://discord.com/channels/558029475837902851/1119133303514071090/1192834516331536464).
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/319590/5efb0dd6-bb67-41bd-85d0-d0780966fc3f)

Support statement for this feature.
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/319590/1905a5be-1c80-4c5e-bc2b-9bbf585fb76f)

**Comment by Muttley** [comment]
I disagree with changing the Foundry default I'm afraid, even as an option.
