### ISSUE TITLE
Multiple Rolls per PC with Clockwise Initiative Enabled

### ISSUE THREAD

**Issue by TheBrianFactor** [Muttley/foundryvtt-shadowdark#662]
During my session this past week, I could not figure out what was happening with Clockwise Initiative.  After reviewing the chat log after session, it appears that when my party was rolling for initiative, the chat log was replicating an entire party's rolls once per player.  Below I've included a screenshot of the first cycle:
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/45749331/b08da346-7fb4-4964-aa63-aa6a13911beb)
Then the chat log repeats an initiative roll for every PC and advertises the "GM rolls for initiative" from every player's name, including the GM.  We for initiative two different ways: 1) each player clicked "roll initiative" on their PC sheet, 2) the GM selected all tokens (PCs and monsters) and added them to the initiative by the right-click menu on tokens.  Both methods repeated the same effect.

Does Clockwise Initiative only need one person to roll for initiative, therefore triggering rolls from everyone else?  Must initiative be rolled by the GM-only?  Or is there a particular way to add characters to combat and have them roll for initiative that we did not use in order to allow Clockwise Initiative to work properly?

**Comment by WisdomOfWombats** [comment]
Yesterday, I had the same experience. Is that a bug, or do I not understand the feature?

**Comment by TheBrianFactor** [comment]
> Yesterday, I had the same experience. Is that a bug, or do I not understand the feature?

I don't work on this project, merely and an elaborate unofficial tester, but I have found what Clockwise Initiative's functionality does.  When you start a combat so that everyone can roll initiative, no matter who clicks Initiative, that Player initiates a roll for everyone and attempts to roll for them.  The easiest work-around (though this may be intended) is that I - as the DM - just roll for one of my monsters and everyone else's initiative will follow.

Since the DM can roll/control every token, it works without errors.  I just let my players know "I'll be rolling all of your initiatives unless this functionality is changed."
