### ISSUE TITLE
Light settings change when turning off light source.

### ISSUE THREAD

**Issue by Miker598** [Muttley/foundryvtt-shadowdark#665]

**Comment by Miker598** [comment]
Light settings (color,shadows,etc) that I add to a prototype token are changed when the light source is extinguished.

**Comment by PrototypeESBU** [comment]
This seems like normal behavior as the light source object should override token settings. It's the light object that determines the light properties not the token.

A quick and dirty way to change the default light settings is to edit `foundry\Data\systems\shadowdark\assets\mappings\map-light-sources.json` and change those values for the torch template or the other light sources type. You'll have to make this change after every update, but it might be a way forward for you.

**Comment by Muttley** [comment]
This should be fixed by #383 when it's implemented.
