### ISSUE TITLE
Bug: Classes and spells fail to open when linked items are deleted or moved

### ISSUE THREAD

**Issue by PrototypeESBU** [Muttley/foundryvtt-shadowdark#667]
When a spell is linked to a class and that class item is moved or removed, the spell will show a class item with a blank name. The spell then errors out when attempting to open it. With the follow error:
![B](https://github.com/Muttley/foundryvtt-shadowdark/assets/147362581/58634981-22ec-43bf-bee7-0751fc74c6bb)
![A](https://github.com/Muttley/foundryvtt-shadowdark/assets/147362581/23cf591f-688a-4d60-b2d5-f92d248275d1)

The Character class item fails to load with the following errors when a linked item such as a talent, weapon, or armor is moved or removed. 
![c](https://github.com/Muttley/foundryvtt-shadowdark/assets/147362581/7ff3badf-c088-447b-8eda-dd83b2cde0a8)

**Comment by Muttley** [comment]
It would probably be best to detect that something is missing and just display a generic "[Missing]" text in that box (and potentially make it read-only to avoid issues).
