### ISSUE TITLE
Bug: Typo in Sleep

### ISSUE THREAD

**Issue by PrototypeESBU** [Muttley/foundryvtt-shadowdark#668]
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/147362581/181579c3-a267-4026-bf4b-fb2237acae33)

Should say "Living creatures" at the start of sentence two.

**Comment by Muttley** [comment]
This is the text from the latest version of the quickstart which we should be using: 
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/853835/53c8fa47-7078-42fa-869a-91265e006277)
