### ISSUE TITLE
Equipping Bracers of Defense unequips other armor

### ISSUE THREAD

**Issue by sjmiller85** [Muttley/foundryvtt-shadowdark#670]
One of my players acquired a set of Bracers of Defense, made available in the compendia.  There was some confusion when they added it to their inventory.  It applied the AC bonus to the character sheet regardless of whether or not it was toggled as equipped, but if they toggled it as equipped as they would be inclined to do since there's an option to toggle equipped, it would unequip their leather armor in order to equip the bracers.  They could not have both the bracers and other armor equipped at the same time.

Can we either have an option for items to allow them to be equipped without unequipping other armor, or maybe put magical pieces of armor that don't amount to a full set in a different category so they don't conflict with other armor?  Maybe disable the "Toggle Equipped" icon for magical items that will automatically add effects like bonuses to AC regardless of whether it's toggled equipped or not?

Steps to reproduce: Add a set of Leather Armor from the compendia to a character sheet.  Click on the "Toggle Equipped" icon to the right of the entry in their inventory.  Add "Bracers of Defense" from the compendia to their inventory.  Click on the "Toggle Equipped" to the right of the entry.  It would equip the Bracers of Defense and unequip the Leather Armor.

**Comment by PrototypeESBU** [comment]
I think this is a long standing bug, but you might be the first to document it. There is a workaround to this that I use to equip armor based magical items. With your leather armor equiped, open the bracers item and toggle equipped from with in the item menu. That should allow you to have both equiped.

**Comment by chrpow** [comment]
Boots of the Cat have the same problem. Interestingly, Cloak of Elvenkind is programmed differently (non-equippable Basic Equipment) despite having basically the same effect as Boots of the Cat.

**Comment by mrstarbuck007** [comment]
@PrototypeESBU I've implemented a fix for this but am unable to create a remote branch in the repo to push my feature branch.  How can I get permission?  This is the first open-source project I've ever wanted to contribute to so I'm not sure how to get started.

**Comment by Muttley** [comment]
> @PrototypeESBU @Muttley I've implemented a fix for this but am unable to create a remote branch in the repo to push my feature branch. How can I get permission? This is the first open-source project I've ever wanted to contribute to so I'm not sure how to get started.

Firstly, thanks for wanting to contribute.

The workflow for this should be you creating a fork of the project, then you create a branch in your own fork to implement the fixes and then create a pull request back to parent repository for review/merge.

GitHub have some documentation/tutorials around this you may find useful: https://opensource.guide/how-to-contribute/#how-to-submit-a-contribution
