### ISSUE TITLE
Bug: Bag of Holding not adding additional slots

### ISSUE THREAD

**Issue by Delgored** [Muttley/foundryvtt-shadowdark#672]
I noticed that the bag of holding isn't adding additional slots to the character.  This was working before.

I even went in and added an effect that added 10 slots and it didn't work.

Thanks,

**Comment by PrototypeESBU** [comment]
The bag should be using the following effect:
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/147362581/efab2dff-1de1-4655-a556-a77f9ee0674f)
