### ISSUE TITLE
Bug: Weapon effects

### ISSUE THREAD

**Issue by PrototypeESBU** [Muttley/foundryvtt-shadowdark#693]
There exists a bug where the effects of weapon attack roll bonus and weapon attack damage bonus, persist on the character if removed from the item. If the effects are added back to the item, the previously set values for both (system.bonuses.attackBonus & system.bonuses.damageBonus) will remain until the values are edited, at which point normal behavior is resumed.

Steps to reproduce:
1. create new actor
2. add new weapon
3. add weapon attack roll bonus and weapon attack damage bonus
4. delete weapon attack roll bonus and weapon attack damage bonus
5. note that effects persist on item

**Comment by Muttley** [comment]
I believe this may be a vaguary of the way Active Effects work in Foundry.  Once effects have been added to a character via an item you need to disable the effect before you can edit it.

Currently we don't have a way of deleting/disabling effects that have filtered down to the actor from an item, but we could enhance the Effects tab to do that (I have some similar code in the Achtung! Cthulhu and Fallout systems).

The workaround is to delete the item, remove the effects from the compendium/world item, and then re-add it.

**Comment by PrototypeESBU** [comment]
A new method for transferring effects was adding in v11 that solves this. Turns out, we had this new method turned off in the code.
