### ISSUE TITLE
Auto Roll NPC HP Re-Rolling

### ISSUE THREAD

**Issue by TheBrianFactor** [Muttley/foundryvtt-shadowdark#714]
When the "Auto Roll NPC Hit Points" setting is toggled on, an NPC token is prompted to reroll HP when changing between scenes.  This happened while an NPC was chasing PCs across scenes.  The NPC token had 4 HP remaining, when changed to the new scene, they rerolled their entire health pool and reset their HP to maximum.

**Comment by Muttley** [comment]
Auto Roll NPC Hit Points occurs when a token is added to a scene, so this is working as designed.
If you don't want this behaviour, disable the option and either use the default, or click the HP header line on the NPC to roll it manually once you've add it.
