### ISSUE TITLE
Include options to manually adjust light timer in the tracker UI

### ISSUE THREAD

**Issue by markschepis** [Muttley/foundryvtt-shadowdark#732]
Would be great to have at least a button to decrease remaining time by 5/10 minutes to support fast forwarding (e.g. party spends 10 minutes searching a room). Would probably apply to all light sources.

Could also include individual sliders for more granular control.

For reference: https://shadowtorch.vercel.app/ (click scroll icon in upper right for additional options and multiple light sources).

**Comment by Muttley** [comment]
You can actually already do this by adjusting the game time using the Simple Calendar (or similar) module.

https://foundryvtt.com/packages/foundryvtt-simple-calendar
