### ISSUE TITLE
Advantage on Magic Missile talent missing from Wizard Class item

### ISSUE THREAD

**Issue by LtDerek** [Muttley/foundryvtt-shadowdark#761]
Zaldini the Red is a pregen character that Shadowdark system has in it's compendium.

When Zaldini the Red casts magic missile, the advantage button is highlighted green, because it's supposed to be cast at advantage.

However this green highlighting property is unique to this pregen. Other wizards do not get it, and even if you delete all of Zaldini's features and change his class, his magic missile retains it's green advantage button. The property seems to be tied specifically to this pregen, from some unseen source that I as DM cannot see or change.

This is hardly a gamebreaking issue, but it would be nice if Zaldini could share the secrets of his cool button. So that I can give this feature to all my wizards.

**Comment by PrototypeESBU** [comment]
Advantage on magic missile is currently trigger via a class talent call "Advantage on Magic Missile". Adding that talent to a character will give you the green advantage button. I agree that there is room for improvement here, as this should be more related to the use of the spell itself.
