### ISSUE TITLE
Advance Torch time 

### ISSUE THREAD

**Issue by PleaseForgetAboutMe** [Muttley/foundryvtt-shadowdark#764]
As a DM of Shadowdark on foundry I will often tell the party that X action (searching niches in a room) will take Y amount of time. I am currently unable to advance the countdown time on foundry to reflect this causing the “actual” time and “display” time of torches to become out of sync. A manual adjustment of time left remaining in the light source menu where I can add/remove toke to the counter would allow me to track this with more ease.

**Comment by Muttley** [comment]
The Simple Calendar module can be used to perform this function: https://foundryvtt.com/packages/foundryvtt-simple-calendar

This is the best way to do this, just install it and use the controls to advance the game time.
