### ISSUE TITLE
Make tier sections in Spell Book collapsable

### ISSUE THREAD

**Issue by Muttley** [Muttley/foundryvtt-shadowdark#796]
Also, when opened by a character should default to having all tiers they can't use yet collapsed by default.

**Comment by PrototypeESBU** [comment]
I'm currently working on moving the tiers to be tabbed sections in the UI update. Does that work?

**Comment by Muttley** [comment]
> I'm currently working on moving the tiers to be tabbed sections in the UI update. Does that work?

Yeah, anything that allows people to just show specific tiers would be fine, as there's a lot of speels on there.

**Comment by PrototypeESBU** [comment]
completed in #769
