### ISSUE TITLE
Bug: Character Generator improperly displays modifiers in stat box

### ISSUE THREAD

**Issue by TheBrianFactor** [Muttley/foundryvtt-shadowdark#799]
As title suggests, using the Character Generator to roll a character, the "Stats" section improperly displays modifiers associated with the rolled ability score.  See picture:
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/45749331/df1f37b2-896a-4251-9eeb-50c1b4211f86)
Proper scores should be:
STR: +3 (incorrect)
DEX: +3 (incorrect)
CON: 0 (correct)
INT: +1 (correct)
WIS: +2 (incorrect)
CHA: 0 (incorrect)

**Comment by ScoobyTchotchke** [comment]
It's worse than that it would seem.  If you click to roll for stats, it doesn't take effect until you roll for any other field in the character generator.  The first time I click on the dice icon for Stats, everything remains as 10's.  It's not until I click on the dice for any other field in the Character Generator that it updates the stats to what I rolled.  If I attempt to re-roll, it doesn't automatically update the select boxes, but the modifiers change to reflect the new rolls.  I have to re-roll another field to get the stat values to show up properly.

**Comment by PrototypeESBU** [comment]
Root cause of this is that .foreach() functions can't work asynchronously.
