### ISSUE TITLE
Classes Displayed Twice in Pull-Downs

### ISSUE THREAD

**Issue by TheBrianFactor** [Muttley/foundryvtt-shadowdark#800]
I'm reconciling my compendium and items and have found that several Caster Classes list [Invalid ID] (no big deal), but when I go to select class, every class is listed twice.  How do I make sure that I do not have duplicates for no reason?  It's driving me mad because I cannot figure it out.  This issue also occurs with things like Talents, Backgrounds, and Ancestry.
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/45749331/0fecdde4-d7a7-40ba-8b2f-41159f442ec7)

**Comment by Muttley** [comment]
You've probably duplicated the classes in multiple compendiums (these all exist in the core system now).  If you don't want to use the core items then you can set the source filter accordingly in the system settings.

**Comment by Muttley** [comment]
No response in over a week.  Closing as invalid.
