### ISSUE TITLE
Enhancement: Update Ranger talent text

### ISSUE THREAD

**Issue by PrototypeESBU** [Muttley/foundryvtt-shadowdark#816]
Kiwi4BBQ wrote:

> It appears like Foundry is using old wording on the ranger's Herbalism class talent. 

![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/147362581/efbd12e4-f3a7-4c82-b1c6-a28d94607ef7)

**Comment by andrewbeard** [comment]
Fixed in PR #819
