### ISSUE TITLE
Bug: Rolling Dice Tour not working

### ISSUE THREAD

**Issue by Korlod** [Muttley/foundryvtt-shadowdark#818]
Step 11 (rolling Hit Dice) will fail either by simply not continuing the tour (no dialog comes up) or sometimes it will start to paint a dialog and instead freeze forcing a complete restart of Foundry to continue.

**Comment by PrototypeESBU** [comment]
Support for tours to be dropped in 2.3.0. Will be replaced by new forms of documentation.
