### ISSUE TITLE
Enhancement: Remove free carry item property

### ISSUE THREAD

**Issue by PrototypeESBU** [Muttley/foundryvtt-shadowdark#836]
This property doesn't seem to have a function.

**Comment by Muttley** [comment]
No it definitely does get used.  It's for things like backpacks where you get the first one for free, but additional backpacks use up slots.

I've just noticed that it doesn't take into account multiple copies of items, only quantities.  So I'll fix that.

**Comment by Muttley** [comment]
Related ticket #839
