### ISSUE TITLE
Sundering property is is a sheet breaking issue

### ISSUE THREAD

**Issue by teacherx333** [Muttley/foundryvtt-shadowdark#846]
The sundering property is not being read by the system.  This was a universal property that was not relying on CS3 to be loaded.  with the pathway being broken this will break any character sheet that has an item with sundering

**Comment by PrototypeESBU** [comment]
This was caused by a corrupted system installation on TeacherX's Foundry. Re-installing the system resolved the issue.

**Comment by teacherx333** [comment]
Thank you guys for the help, sorry I am just a dufus end-user.
