### ISSUE TITLE
Bug: Ranged attacks on melee weapons not showing correctly

### ISSUE THREAD

**Issue by teacherx333** [Muttley/foundryvtt-shadowdark#852]
when I create a dagger, then add a lone weapon damage of one on the effects page, the melee reflects this accurately, yet the ranged entry shows ad addition +1 on the damage.  i.e. i get an attack number and then 1d4+1 on melee, but for ranged I get the attack number and the 1d4+2 on damage.

I can delete all daggers and remake them and all goes well until I give the one "serrated" dagger a +1 damage. then it goes to heck.

**Comment by Muttley** [comment]
Please can you provide and export of the character which is showing this problem, and the dagger item itself as well so I can look into it.

**Comment by teacherx333** [comment]
Prototype said that he ID'd this bug already.

**Comment by teacherx333** [comment]
I will provide what you request.  I hope this helps, yet as stated
Prototype says he found this when making the video.

**Comment by Cussa** [comment]
I think I found the cause of the issue.

On this line https://github.com/Muttley/foundryvtt-shadowdark/blob/d9700f47c1016cdae45a82d28845b9703803471e/system/src/documents/ActorSD.mjs#L502, you are adding the `item.system.bonuses.damageBonus`. However, you are added that on a previous calculation: https://github.com/Muttley/foundryvtt-shadowdark/blob/d9700f47c1016cdae45a82d28845b9703803471e/system/src/documents/ActorSD.mjs#L457-L459

So, removing the line 502 should solve the problem.

**Comment by teacherx333** [comment]
Thank you for finding the issue.  Is this going to be in the next patch?
