### ISSUE TITLE
Please amend "Thrown" weapon property to align  with v4-8

### ISSUE THREAD

**Issue by teacherx333** [Muttley/foundryvtt-shadowdark#868]
The weapon property states it sues STR or DEX.

**Comment by anders-tech** [comment]
Thrown Property should read: 
> You may throw this 
weapon to make a ranged attack 
 with it using STR or DEX.

**Comment by PrototypeESBU** [comment]
Thrown attack should read:

> You may throw this weapon to make a ranged attack 

 with it using STR or DEX.
