### ISSUE TITLE
[BUG] Unable to pick up dropped light source

### ISSUE THREAD

**Issue by johncarney** [Muttley/foundryvtt-shadowdark#870]
Per #301 and #388, when a player drags a light source from their inventory onto a map, a "Dropped Torch" actor is created. However from there the torch cannot be moved to any actor's inventory.

Dragging the Dropped Torch token onto a token or actor's sheet has no effect (other than moving the Dropped Torch token). Clicking on the Dropped Torch actor in the actor's tab does bring up a dialog with a "Pick up Lightsource" button. This looks promising, but it does not work. When a player tries it, the following error appears in the GM's console:

<img width="572" alt="Screenshot 2024-09-02 at 5 21 16 PM" src="https://github.com/user-attachments/assets/cd2376d4-133a-47ca-ac49-6931de0339b8">

When a GM tries using the "Pick up Lightsource" they get a dialog asking them to choose an actor, but when an actor is chosen and the "Select" button clicked, the following appears in the console:

<img width="572" alt="Screenshot 2024-09-02 at 5 20 45 PM" src="https://github.com/user-attachments/assets/b4f97eb6-4345-404f-878c-b82777f314b8">

# Steps to reproduce

1. Place a player-owned actor carrying a torch onto a map.
2. Open up the actor's sheet and select the "Inventory" tab. 
3. Drag the torch on to the map. A token will appear on the map along with a "Dropped Torch" actor in the actor's tab.
4. Click on the Dropped Torch actor. A dialog will appear.
5. Click on the "Pick up Lightsource" button on the dialog. A second dialog will appear.
6. Select the actor in the dialog and click on the "Select" button.

At this point I would expect the torch to be moved into the chosen actor's inventory and the dropped torch token be removed from the map along with the corresponding actor. None of that happens. Instead an error shows up in developer console.

Note that if the above actions are performed by a player the experience is basically the same except that they do not get a choice of actor and the error that shows up in the developer console is different.

# Workaround

One way to work around this would be for the GM to create a "Linkboy" actor owned by all players. With that the players can drag torches to the linkboy actor's sheet. Obviously this is quite clunky, but it at least lets players "drop" torches and other lightsources to fixed positions on the map if needed.

**Comment by PrototypeESBU** [comment]
This looks to be a real bug. Thanks for the detailed report. I'll see about getting a fix out in the next patch. A faster workaround is to right click on the token hub flame button to pick up the torch. This method seems to work fine for me.
![image](https://github.com/user-attachments/assets/acb3f514-6eef-4457-b154-d1e3638b5964)

**Comment by PrototypeESBU** [comment]
I see the problem here. The pick up function expects you to always be accessing the dialogs from the scene token. Opening the light actor from the actor's tab causes it to fail.

**Comment by johncarney** [comment]
Awesome. I did it see the flame icon on the token HUD. When do you think you'll be able to push out your next patch release? I'm also interested in seeing the updates to the ShadowDarklings import :)

**Comment by PrototypeESBU** [comment]
Fixed and waiting to go out with 3.1.0.
