### ISSUE TITLE
Enhancement: Add more details to the character generator

### ISSUE THREAD

**Issue by PrototypeESBU** [Muttley/foundryvtt-shadowdark#874]
Add class and ancestry descriptions in the details tab

**Comment by Muttley** [comment]
It would be nice if the character generator opened the character sheet for you after creation.  I frequently need to reference it when doing the initial level up because I've forgotten what the ability scores were and I've rolled a choice of ability improvements.

**Comment by PrototypeESBU** [comment]
That makes sense.

**Comment by Muttley** [comment]
> That makes sense. The problem is making sure the character sheet doesn't cover up the level up screen. Maybe we could just list stats on the level up sheet?

Maybe adding a button to toggle the character sheet would work then?
