### ISSUE TITLE
Add additional padding to blockquote style so text doesn't blend into decorations

### ISSUE THREAD

**Issue by nschoenwald** [Muttley/foundryvtt-shadowdark#896]
It's very cool that the block quote styling in journals matches the Shadowdark design, but it makes them hard to read. I specificially dislike that the white text bleeds into the white edge on the left and right sides.

<img width="642" alt="image" src="https://github.com/user-attachments/assets/5a420361-7320-4d9b-ad50-d3c4b30bee58">

**Comment by ScoobyTchotchke** [comment]
Can confirm this can get a little out of hand.

![image](https://github.com/user-attachments/assets/fa04ec38-afe6-46cf-b38a-f2707d5fd948)

**Comment by Muttley** [comment]
As a workaround you can always just add a few more line breaks so the text isn't as long...
