### ISSUE TITLE
Can't paste Shadowdarklings JSON if previously copied text object

### ISSUE THREAD

**Issue by ScoobyTchotchke** [Muttley/foundryvtt-shadowdark#902]
Foundry Version: v12 (stable) Build 331
Shadowdark Version: v3.1.3
Web Browser: Chrome v129.0.6668.59 (Official Build) (64-bit)
Active Modules: Raise My Hand, Dice So Nice!, Dice Tray, Library: Chat Commands, Monk's Chat Timer, Monk's Little Details, Multilevel Tokens (by Beneos), socketlib, Token Ease

When trying to import JSON from Shadowdarklings into the Actor's tab in Foundry, if you previously copied a text object, it will paste a copy of the text object instead of the JSON.  I have to refresh Foundry to flush the text object out of my clipboard before attempting to copy and paste in the JSON into the character importer.

Steps to reproduce:

1. Create a text object on the canvas
2. Select the text object and copy it (Ctrl-C)
3. Go to Shadowdarklings
4. Create a character and select "Copy to Clipboard" at the bottom and press the "JSON" button, and click ok on the browser prompt to clear it out
5. In Foundry, go to the Actors tab and click on Import at the very bottom
6. Click on the box in the center of the pop-up that says "Paste Character JSON Here" and paste (Ctrl-V)
7. A blue notification will pop up saying a text object was copied, the JSON will not paste into the pop-up

When you close out of the importer, you may notice a bunch of the text objects you created & copied earlier pasted all over the canvas.  Refresh the browser, and attempt to paste the JSON back into the pop-up and it will work as expected.

**Comment by PrototypeESBU** [comment]
Good find. I did notice some weirdness with pasting into the importer, but this is a good write up of a repeatable bug. I'll get this fixed up for next patch. Thanks for your bug reports! Very helpful.
