### ISSUE TITLE
Importing Wizards from Shadowdarklings returns "Plus2INTOrPlus1Casting" errors

### ISSUE THREAD

**Issue by ScoobyTchotchke** [Muttley/foundryvtt-shadowdark#903]
Foundry Version: v12 (stable) Build 331
Shadowdark Version: v3.1.3
Web Browser: Chrome v129.0.6668.59 (Official Build) (64-bit)
Active Modules: Raise My Hand, Dice So Nice!, Dice Tray, Library: Chat Commands, Monk's Chat Timer, Monk's Little Details, Multilevel Tokens (by Beneos), socketlib, Token Ease

When importing wizards from Shadowdarklings, if the talent "+2 to Intelligence stat or +1 to wizard spellcasting checks" is selected, for each instance Foundry complains that it cannot find "Plus2INTOrPlus1Casting" and only lets you partially import a character.

Steps to Reproduce:

1. Go to Shadowdarklings.net and generate a wizard character
2. Make sure your generated character has at least one or more talents that require them to either take +2 to INT or +1 to spellcasting checks.
3. Export the character as JSON
4. In Foundry, use the importer in the Actors tab to paste the JSON for the wizard
5. You should see a block in the pop-up that says "ITEMS NOT FOUND" with one row of "Plus2INTOrPlus1Casting" for each of the above talent in the character sheet.

![image](https://github.com/user-attachments/assets/41b9fd16-4fab-4901-b0a4-3b4fee3227f2)

Example wizard JSON file: 
[Snik.json](https://github.com/user-attachments/files/17140999/Snik.json)

**Comment by PrototypeESBU** [comment]
When doing a partial import do the talents still get added correctly? I think this is due to some extra data shadowdarklings puts in, but should be safe to ignore.

**Comment by ScoobyTchotchke** [comment]
It does appear that it gets added correctly.  The error messages seem to be a mistake, but should probably be cleaned up to not confuse users.

**Comment by PrototypeESBU** [comment]
All good. I'll get this fixed up for next patch.
