### ISSUE TITLE
[Bug] There's always an extra space between special attack name and effect

### ISSUE THREAD

**Issue by nschoenwald** [Muttley/foundryvtt-shadowdark#906]
Am I doing something wrong or is this a bug?

<img width="409" alt="image" src="https://github.com/user-attachments/assets/69a574d5-8166-4fe9-97e0-cad3a0e19a3d">

**Comment by PrototypeESBU** [comment]
Can you post the stat block text you used to create this?

**Comment by nschoenwald** [comment]
<img width="659" alt="image" src="https://github.com/user-attachments/assets/878b22a8-a51e-41c1-a8d8-2d0527460c15">

[fvtt-Actor-dolorous-ichor-blob-6sRpdBXEMLahQ379.json](https://github.com/user-attachments/files/17180840/fvtt-Actor-dolorous-ichor-blob-6sRpdBXEMLahQ379.json)

**Comment by PrototypeESBU** [comment]
What is the text you are posting into the monster importer?

**Comment by nschoenwald** [comment]
I created the monster from scratch, I didn't use any importer.

**Comment by PrototypeESBU** [comment]
My bad, I misunderstood this at first. It's not you, it's an actual bug. There's an extra space there that shouldn't be there when there is no to hit modifier. Thanks for pointing this out.
