### ISSUE TITLE
Added +1 AC Dual Wield active effect to talent of same name which can be toggled on/off as needed on the character sheet now

### ISSUE THREAD

**Issue by PrototypeESBU** [Muttley/foundryvtt-shadowdark#909]
Lilothyn writes: 
With +1 AC Dual Wield talent, when I have 2 melee weapons equipped, I don't get the AC bonus. There's no way to specify which hand each weapon is on, as far as I can tell, so maybe it's just not implemented yet?

**Comment by PrototypeESBU** [comment]
It's a black lotus talent. #4 on the list.

> You gain +1 to your AC when wielding a melee weapon in each hand

**Comment by Muttley** [comment]
Ah, OK.  I don't think we'll be going down the route of tracking which weapons are in which hand.

This would be better served with the standard +1 AC Talent, but we need to display Active Effects on the Effects tab of the character sheet so the bonus can be toggled on/off when needed, which is coverd in #921

**Comment by PrototypeESBU** [comment]
Yes, this is exactly what I was envisioning.

**Comment by Muttley** [comment]
Relies on #921
