### ISSUE TITLE
Enhancement: Refactor Art mappings to use the built in v12 function

### ISSUE THREAD

**Issue by PrototypeESBU** [Muttley/foundryvtt-shadowdark#911]
In v12, there is a built in way of mapping artwork in compendiums. Investigate removing system built in and converting legacy mapping flags over to the new format. Existing mapping files appear compatible with the new build in method. Artwork mappings will then be managed in the core settings.

new module flags
```
"compendiumArtMappings": {
   "shadowdark": {
      "mapping": "modules/art-module/mapping-system-id.json",
      "credit": "<em>Portrait and token artwork by Art Module.</em>"
    }
}
```

**Comment by Muttley** [comment]
> In v12, there is a built in way of mapping artwork in compendiums. 

Interesting.  I was not aware they added that.
