### ISSUE TITLE
Weapon Attack Damage Bonus effect not applying during roll.

### ISSUE THREAD

**Issue by silentcatfart** [Muttley/foundryvtt-shadowdark#913]
Boon added to character using: 

Pre-defined effect: Weapon Attack Damage Bonus. 
system.bonuses.damageBonus
Add
2
Apply Effect to Actor = True

Boon shows active yet no bonus applied to damage roll

**Comment by PrototypeESBU** [comment]
Weapon Attack bonus only applies when attacking with the weapon it is attached to so adding it to a boon will have no effect. For this case, use meleeAttackBonus or rangedAttackBonus instead.

**Comment by silentcatfart** [comment]
Ah I see. Thank you for taking time to respond. Next time I’ll throw it in the discord channel to get a weigh in before reporting as a bug. 

I’m newish to Shadowdark but not Foundry and I was just trying to translate the Dragonfly Horde pdf Kelsey crowdsourced into a module for my players. Didn’t realize this mechanic wasn’t possible as written.

I’ll close this one out!
