### ISSUE TITLE
The Black Lotus Talents table has 3 mistaken/mis-placed entries

### ISSUE THREAD

**Issue by bane73** [Muttley/foundryvtt-shadowdark#926]
The Black Lotus Talents table in the Compendium has the following mistaken/mis-placed entries (as compared to the Shadowdark source):

- Result-1, "Gain two Black Lotus talents", is mistakenly included in the table but should not be -- this talent instead belongs only on the Ras Godai Talents table (which it correctly does)
- Result-6, "Triple Damage Assassin", is mistakenly-located as Result-6 but should instead be Result-1
- Missing Result from the source, "Advantage on DEX to sneak/hide" (Result-6 in the source), is missing entirely from the table

![bug-2](https://github.com/user-attachments/assets/d97d3faa-f00a-44ee-b99d-76ed8e0fc5fc)

**Comment by PrototypeESBU** [comment]
Thanks for pointing this out! We'll get it fixed for next patch.

**Comment by PrototypeESBU** [comment]
I think you are using an outdated version of the cursed scroll zine. The talent table in Foundry is correct according to the latest version of cursed scroll #2 zine (v2-2).

**Comment by PrototypeESBU** [comment]
I think you are using an outdated version of the cursed scroll zine. The talent table in Foundry is correct according to the latest version (v2-2) of cursed scroll 2 zine.

**Comment by bane73** [comment]
Ah! Thank you, looks like I missed that wave of updates. Apologies for the red herring.
