### ISSUE TITLE
Hauler talent in Compendium shows duplicate effects

### ISSUE THREAD

**Issue by Muttley** [Muttley/foundryvtt-shadowdark#93]
![image](https://user-images.githubusercontent.com/853835/226552701-f8346e75-039d-40c8-8be3-4d395e28f0e1.png)

If you import it and delete one of the items, both are deleted.

Exporting the Item data doesn't show two Effects for some reason:

```json
	"effects": [{
		"label": "Hauler",
		"icon": "icons/containers/bags/sack-leather-tan.webp",
		"origin": "Compendium.shadowdark.talents.7JTDRLtHc6FOrIEc",
		"changes": [{
			"key": "system.bonuses.hauler",
			"mode": 5,
			"value": "true",
			"priority": null
		}],
		"disabled": false,
		"transfer": true,
		"_id": "rqplFhIShnvmV0U4",
		"duration": {
			"startTime": null,
			"seconds": null,
			"combat": null,
			"rounds": null,
			"turns": null,
			"startRound": null,
			"startTurn": null
		},
		"tint": null,
		"flags": {}
	}],
```

Also, as this is a pre-canned effect, shouldn't it appear in the Talent Type(s) list?

**Comment by bakbakbakbakbak** [comment]
On the Talent Type(s), I opted to make it a custom talent instead, as it will only be useful for this specific talent as it has a boolean flag!
