### ISSUE TITLE
Unable to edit/modify active effects on Items

### ISSUE THREAD

**Issue by TheBrianFactor** [Muttley/foundryvtt-shadowdark#964]
The Shortsword of the Thief (core item) has an optional +2 to attack and damage rolls if the wielder is a Halfling or Thief.  In this case, it is being wielded by a Thief.  For flavor, I copied this item and changed the weapon type to Dagger, adding the Thrown and Finesse traits.

The renamed "Blade of the Thief" shows on the Abilities tab as such:
![image](https://github.com/user-attachments/assets/ac6a47ae-6f7a-43a8-b610-f1550319bfb2)

Melee Attacks - +5 (close), 1d4+1.  _These should be +6 (close), 1d4+2_.
Ranged Attacks - +5 (close), 1d4+1.  _These should be +6 (near), 1d4+2_.

The item setup is:
![image](https://github.com/user-attachments/assets/42933cb8-aed2-44cf-98bf-4f1771d40bca)
![image](https://github.com/user-attachments/assets/40e12924-14cd-416d-96c6-e744787bd827)

I also, now, am unable to open the edit menu using the edit icon to the right or change the "Toggle Effect" status.  However, the weapon will always apply +1 weapon/damage even if it is toggled off and the +2 is toggled on.

Please help.

**Comment by Muttley** [comment]
Looks like there's a bug in the way we handle effectes on Items.
