### ISSUE TITLE
Enhancement Request:   Generic Ability

### ISSUE THREAD

**Issue by Delgored** [Muttley/foundryvtt-shadowdark#973]
Hi, I was wondering if it was possible to get a generic ability, similar to a class ability.

![image](https://github.com/user-attachments/assets/018d6907-bf8e-47ad-a132-2bd0c96de9fb)

And as well have an option to have it not linked to an ability check.

Just use 1/day or 3/day or whatever is set.  So instead of a roll, it's just a use.

That way on the abilities tab it doesn't go under the Class Abilities, but just a section under abilities.

Thank you,
Delgore.

**Comment by Delgored** [comment]
I forgot the arrow pointing to stealthy.

**Comment by Muttley** [comment]
> And as well have an option to have it not linked to an ability check.
>
> Just use 1/day or 3/day or whatever is set. So instead of a roll, it's just a use.

You can do both those already just by leaving the Ability Check setting on the Special Apility empty:

![image](https://github.com/user-attachments/assets/98255901-d872-4af7-840a-076c429a368d)

**Comment by Muttley** [comment]
I propose we just name the section Special Abilities, rather than insert the current class name of the character.  That way it's more generic and can be used by both class abilities and general abilities.

**Comment by Delgored** [comment]
That sounds great.   Makes it easier than dividing it up.

Thanks
